### ISSUE TITLE
Orchestrator deployment missing secret

### ISSUE THREAD

**Issue by tariksimsek** [ManageIQ/manageiq-pods#1047]
Describe the issue you are having and what you expected to happen.
Orchestrator can't find secret . I believe it is not created from operator.

Describe the steps to reproduce, including any log snippets and stack traces that will help diagnose.
![image](https://github.com/ManageIQ/manageiq-pods/assets/118598396/2b7de335-7377-4991-a36f-db4bb4da8c31)

Describe your environment, including

Version
Latest
Environment
Rancher K8s 1.26

**Comment by nasark** [comment]
@tariksimsek Please check your kafka deployment. The strimzi operator deploys services in the following order: `zookeeper -> kafka -> entity operator`. The entity operator manages the `manageiq-user` secret which means that either the entity-operator pod did not deploy correctly or you simply need to wait for the pod to spin up.

If you could list your pods that would help as well `kubectl get pods`

**Comment by bdunne** [comment]
Please re-open if this is still an issue.
