### ISSUE TITLE
PostgreSQL Password should be Autogenerated

### ISSUE THREAD

**Issue by simon3z** [ManageIQ/manageiq-pods#105]
Current ability of configuring a password for PostgreSQL (`DATABASE_PASSWORD`) is handy but in case it's not defined it shouldn't be a known default password `smarvm` but rather a random generated one (and stored as a secret).
IIRC password generation is well supported and easy to use in Kubernetes/OpenShift (for inspiration you can look at Heapster/Hawkular).

cc @fbladilo @bazulay

**Comment by fbladilo** [comment]
@simon3z This is the way we had the database password set originally, auto-generated. I can't recall if manually setting the password via template param (-p DATABASE_PASSWORD) overrides the auto-gen call on template, need to verify. I will look at the examples as well. @bazulay thoughts?
