### ISSUE TITLE
Application and Database Volume Capacity

### ISSUE THREAD

**Issue by simon3z** [ManageIQ/manageiq-pods#106]
Given the recent tests I had, I think the default values should be something like:

- `APPLICATION_VOLUME_CAPACITY=5Gi`
- `DATABASE_VOLUME_CAPACITY=15Gi`

Also remember that currently the backups at each restart could easily fill the application volume.

cc @fbladilo @bazulay 
(Let me know if I should be sending a PR)

**Comment by fbladilo** [comment]
@simon3z agreed our default values are definitely low and not realistic at all, please keep in mind we are working on #103 which should reduce the size of backups considerably.
