### ISSUE TITLE
Postgres POD needs log rotation

### ISSUE THREAD

**Issue by bazulay** [ManageIQ/manageiq-pods#110]

**Comment by bazulay** [comment]
opened this issue on the official sclorg postgresql-container repo,
https://github.com/sclorg/postgresql-container/issues/168

**Comment by bazulay** [comment]
Leaving this issue still open for tracking

**Comment by fbladilo** [comment]
@bazulay I just confirmed that PG log rotation is enabled daily on the images via postgresql.conf.

**Comment by bazulay** [comment]
Per comment above closing the issue
