### ISSUE TITLE
Unable to deploy custom operator following the README

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-pods#1133]
When I follow the READMEs https://github.com/ManageIQ/manageiq-pods/blob/master/README.md#building-images and https://github.com/ManageIQ/manageiq-pods/blob/master/manageiq-operator/README.md#running-manageiq-under-operator-control after the `oc create -f` step the operator fails to deploy due to a missing service account:

![image](https://github.com/user-attachments/assets/2c7e3142-e7ca-405b-8ca1-dcc16cb71fdb)

**Comment by agrare** [comment]
cc @bdunne do you know what I'm missing here?

**Comment by bdunne** [comment]
Did you follow the "preparing the namespace" instructions [here](https://www.manageiq.org/docs/reference/latest/installing_on_kubernetes/index.html#preparing-the-kubernetes-namespace)? The error says it can't find the service account.

**Comment by agrare** [comment]
Thanks! That is what I was missing
