### ISSUE TITLE
move container image build process to CentOS CI

### ISSUE THREAD

**Issue by goern** [ManageIQ/manageiq-pods#132]
Manageiq container build process seems to be working around some Docker Hub auto build limitations. Using [CentOS CI](https://wiki.centos.org/QaWiki/CI/GettingStarted) could be a way to improve the structure of MIQ container images and to eliminate MIQ requirements like https://github.com/ManageIQ/manageiq-pods#increase-maximum-number-of-imported-images-on-imagestream

**Comment by carbonin** [comment]
We removed image streams from the templates. Are there any other issues moving the build would solve?

We are debating moving the builds to a separate system which the core team would operate so we can encode dependent container builds better. Does Centos CI offer something like that?

**Comment by goern** [comment]
I dont know what you mean be the second section, but on CentOS CI you can create build pipelines structures as you want....

**Comment by carbonin** [comment]
We're going to build and push images nightly using [the new build script](https://github.com/ManageIQ/manageiq-pods/blob/4c7acbbeb288caaf97ff4738675517b9beb766f1/bin/build) on the same machine that builds the appliance images.
