### ISSUE TITLE
Embedded ansible install loops?

### ISSUE THREAD

**Issue by stobias123** [ManageIQ/manageiq-pods#158]
Let me know if this is the wrong repo for this issue but I can't install the embedded ansible role...

When I switch the role on and save I get notifications nonstop that it's activating, but it never seems to complete. Still pretty new to ManageIQ - any pointers would help, even if it's just where to start digging in logs.

![image | 200px ](https://user-images.githubusercontent.com/590677/26992090-e7112086-4d11-11e7-9ea9-a56a45143289.png)

**Comment by carbonin** [comment]
This is a bit the wrong location, but the link you'll want to read up on is http://talk.manageiq.org/t/howto-setup-embedded-ansible/2291

**Comment by stobias123** [comment]
Hmm maybe I'll move to the MIQ repo... but per red hat I shouldn't need tower https://access.redhat.com/articles/3062211

**Comment by carbonin** [comment]
You wont need tower if you're running CloudForms, but ManageIQ does need a separate license.
