### ISSUE TITLE
Schema not installed in external postgresql DB

### ISSUE THREAD

**Issue by hahnn** [ManageIQ/manageiq-pods#166]
Hi,
Just tried to deploy ManageIQ using the external DB template.
I can see the external database is contacted but the pod ended in error and keep restarting because the database schema is never installed in the database:

== Checking memcached:11211 status ==
memcached:11211 - accepting connections
Error something seems wrong, we need at least two parameters to check service status
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec': PG::UndefinedTable: ERROR:  relation "miq_databases" does not exist (ActiveRecord::StatementInvalid)
: LOCK TABLE miq_databases in SHARE ROW EXCLUSIVE MODE
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract_adapter.rb:590:in `block in log'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
	from /var/www/miq/vmdb/lib/extensions/ar_table_lock.rb:17:in `block in with_lock'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.4/lib/active_record/transactions.rb:211:in `transaction'
	from /var/www/miq/vmdb/lib/extensions/ar_table_lock.rb:15:in `with_lock'
	from /var/www/miq/vmdb/lib/evm_database.rb:69:in `seed'
	from /var/www/miq/vmdb/lib/evm_database.rb:50:in `seed_primordial'
	from /var/www/miq/vmdb/app/models/miq_server.rb:179:in `start'
	from /var/www/miq/vmdb/lib/workers/evm_server.rb:27:in `start'
	from /var/www/miq/vmdb/lib/workers/evm_server.rb:48:in `start'
from /var/www/miq/vmdb/lib/workers/bin/evm_server.rb:4:in `<main>'

**Comment by carbonin** [comment]
Yeah, that should be fixed by https://github.com/ManageIQ/manageiq-pods/pull/164

Sorry about that
