### ISSUE TITLE
Openshift master config changes

### ISSUE THREAD

**Issue by mberube9** [ManageIQ/manageiq-pods#191]
The requirement to change the Openshift master config file to deploy MIQ is not best practice.  

Any way we can avoid making this change:
**maxImagesBulkImportedPerRepository: 100**

This is an issue for automating the deployment of MIQ as it would require a cluster restart and approval for a cluster setting change.

**Comment by fbladilo** [comment]
@mberube9 This one is difficult, I agree that in general restarting your master to have these settings applied is disruptive. The rationale behind the increase of maxImagesBulkImportedPerRepository is a two part : 

* We use DockerHub to auto-build upstream images, by default we build multiple MIQ releases which are expressed as tags : "latest" , "euwe" , "euwe-2" from their corresponding branches. We also different images from this main repo, an example of this are the frontend and backend images.

I'm not sure this is the case for other projects but the amount of images in our repos grows continuously as we publish new releases. As of today, the miq-app IS which sources from DH manageiq-pods repo has more than 30 images in it : 

```
[root@franco-ocp-master ~]# oc describe is miq-app | grep Unique
Unique Images:		36
```
* The default OpenShift maxImagesBulkImportedPerRepository value of 5 is low, this caused many random image pull failures for users during deployments, the IS will not import the tag that they were requesting and fail, we went ahead and documented this parameter increase.

Some possible solutions to alleviate these ocurrences : 

1. We request a default value increase for this parameter better suited for medium sized image repos. I think we should at least raise this issue. I would also point that it would be smarter to import the latest built (active) tags first, in that order. So during an import at least you will know OpenShift tried to get you the most active images up to the limit for that repo.

2. We split the application images in their own repos, pretty much the same as postgresql, ruby, etc. This will keep the number of tags/images to a more reasonable number, and also allow us to use the latest tag (which is treated specially in OpenShift) for all images that are tracking master. This is no guarantee we will not reach the import limit, eventually as we go through releases we will start populating the repos as well, perhaps maintaining up to certain release would make sense as policy.

More ideas/comments/corrections : @simaishi @carbonin @bdunne

**Comment by simon3z** [comment]
@fbladilo IIUC this is "fixed" by https://github.com/ManageIQ/manageiq-pods/pull/205
Do you think we can close this or we can still do better than that?

**Comment by carbonin** [comment]
I'm going to close this this as the requirement is no longer in place as of #205.

Additionally, I don't see a use for image streams moving forward. The re-architecture effort will more than likely move the image names into the manageiq configuration within the application or they will be defined some other way within the app, so there will be no need to identify them in the OpenShift interface. Because of this I think this solution should suffice for the long term.
