### ISSUE TITLE
Postgres pod "fails" on initial deployment

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-pods#193]
It seems the postgres pod, on initial deployment goes all the way through the setup and a the very end fails with exit code 127.  Then, it goes down, is rescheduled, and when it comes back up, goes through the rescheduling code, which sees that the PV was created properly, and just starts.

In the end it "works", but it is disconcerting to see if fail before being successful.

**Comment by fbladilo** [comment]
@Fryguy What does oc logs <pg-pod> show on the first failure? Usually PG is quick to come up once the image is pulled. (~1min).

**Comment by Fryguy** [comment]
Can I still get the logs?  It dies and is respawn super-quick.  I only notice at all because the pod goes from light blue to orange, I see exit code 127 in the comment, and then quickly to light blue then dark blue

**Comment by fbladilo** [comment]
@Fryguy I would recommend using the CLI for debugging, one quick way to find out what is happening with the PG Pod is to disable the liveness probe on the template.
 
`oc edit template manageiq` , adjust, save and redeploy. 

Alternatively you can achieve a similar behavior by increasing "initialDelaySeconds" on the PG DC to a large value in seconds. This will give you plenty of time to debug and inspect logs on the pod. This value is [here](https://github.com/ManageIQ/manageiq-pods/blob/master/templates/miq-template.yaml#L505)

**Comment by carbonin** [comment]
I haven't seen this in quite a while ... as I recall it was only happening in smaller environments (minishift).

I'm going to close it for now. If it happens again I would re-open it against the PG image and see if there's something we can do there.
