### ISSUE TITLE
httpd pod does not route traffic to manageiq

### ISSUE THREAD

**Issue by ilackarms** [ManageIQ/manageiq-pods#202]
I have everything deploying successfully:

```
[root@ocp-master01 manageiq-pods]# oc get pods
NAME                       READY     STATUS      RESTARTS   AGE
httpd-1-k8rl5              1/1       Running     0          4h
manageiq-0                 1/1       Running     1          4h
memcached-1-zj7bz          1/1       Running     0          4h
miq-app-1-build            0/1       Completed   0          4h
miq-app-frontend-1-build   0/1       Completed   0          4h
postgresql-1-kj64m         1/1       Running     0          3h
```

all pods are healthy, and the httpd route is up:

```
NAME              HOST/PORT                           PATH      SERVICES   PORT      TERMINATION     WILDCARD
routes/httpd      httpd-cfme.<ip>.nip.io                httpd      http      edge/Redirect   None
```

however, the httpd pod isn't routing traffic to the manageiq pod:

![screenshot from 2017-08-21 16-04-00](https://user-images.githubusercontent.com/5974898/29520603-63d06026-868a-11e7-8e92-7e15e680a358.png)

is it possible I have configured something improperly in my setup? the template i  am deploying from is here: 
https://github.com/ilackarms/manageiq-pods/blob/master/templates/miq-template.yaml

please let me know any other info that would help debug this issue.

**Comment by fbladilo** [comment]
@ilackarms Scott closing this one since it was a typo on template...

**Comment by ilackarms** [comment]
@fbladilo yep! would have closed it myself but i figured I'd wait for the typo to be fixed

**Comment by carbonin** [comment]
@fbladilo @ilackarms What was the issue here?

Is there something that needs to be fixed in the template? Could you guys give some more details here either way? Thanks.

**Comment by fbladilo** [comment]
@carbonin I gave a workaround to @ilackarms on a gist template but it had a typo, double volumemount section was preventing the httpd cm to inject/apply. He rectified locally, the real fix for these issues on OCP is in : https://github.com/ManageIQ/container-httpd/pull/14

**Comment by carbonin** [comment]
Ah, thanks @fbladilo, 

>  i figured I'd wait for the typo to be fixed

Made it sound like there was a bug in the template on master.

**Comment by ilackarms** [comment]
sorry, my mistake
