### ISSUE TITLE
manageiq:frontend-latest - Failed to get D-Bus connection: Operation not permitted

### ISSUE THREAD

**Issue by LarsMilland** [ManageIQ/manageiq-pods#206]
Hi

I have been following the guides with templates here on getting ManageIQ running on OpenShift. 

We are running OpenShift origin 1.5.1 on RHEL 7.3, and ManageIQ with its Ruby on Rails parts launches fine in the manageiq-pods:frontend-latest image as OpenShift pods. But the system is not coming all online, as the Apache httpd server that would run as a systemd controlled services is not starting.

It looks like the systemd system is not working at all, as a simple "systemctl status" complains:

Failed to get D-Bus connection: Operation not permitted

The pod is launched with Security Context Constraint of "privileged", and as such should access to the resources it would need.

We have other pods on same OpenShift environment that we can get working with systemd services inside, so it must be something in the manageiq Docker images that is stopping us here or maybe in the permission/privilege setup on the serviceaccounts used.

Any suggestions? Maybe just on where to look for errors inside the pod?

Best regards
Lars Milland

**Comment by carbonin** [comment]
I think this likely has something to do with the issue here https://github.com/ManageIQ/container-httpd/pull/14

I would expect this would apply to the httpd container though, not the frontend one as the frontend container is not supposed to be using systemd.

**Comment by LarsMilland** [comment]
Ok - I will take a look at how the httpd container runs then, and see if it is actually supposed to run with that. But I have difficulties to see how a httpd container in another pod can work as reverse proxy to the manageiq pod, where if else I understand things correct the ruby process only binds to localhost/127.0.0.1 ip and not the hostname ip. If that is the case I can't see how the httpd pod ever can catch manageiq pod.

**Comment by carbonin** [comment]
The httpd pod is going to be used for external authentication which requires running with systemd (that work is in progress). We also run httpd on the front-end container to push requests to the ruby processes, but we don't use systemd to run httpd there.

**Comment by LarsMilland** [comment]
Ok. Also undersgood. But the httpd server is not running on the manageiq pod either.

**Comment by gordillo-ramon-redhat** [comment]
I am facing the same issue.

@carbonin , BTW, what is the reason for an httpd in front of  manageiq, and the ha-proxy router + service (as a lb) does not fulfil the requirements?

**Comment by fbladilo** [comment]
This issue is addressed on https://github.com/ManageIQ/container-httpd/pull/14

**Comment by carbonin** [comment]
@gordillo-ramon-redhat I think I mentioned that in https://github.com/ManageIQ/manageiq-pods/issues/206#issuecomment-324343043; we're not using it for load-balancing, but rather for the external authentication modules.

I'm going to close this as the fix for the httpd pod has been merged.
