### ISSUE TITLE
Rename miq-sysadmin service account

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-pods#213]
When running on a full OpenShift cluster the miq-sysadmin scc is not needed for the httpd auth container. This is because the oci-systemd hooks take care of the necessary capabilities needed for systemd to run in the container.

These hooks do not run on minishift.

I think it would be better for the service account to be called miq-httpd; then we can document what scc should be added to the service account based on the environment you are using.

cc @Fryguy @fbladilo @bdunne

**Comment by fbladilo** [comment]
@carbonin 👍 I agree, is only conditionally needed for minishift. BTW, looks like the minishift OCI systemd hooks issue that we opened is getting some traction : 

https://github.com/minishift/minishift/issues/1299
