### ISSUE TITLE
RFE/Question - Turn PV examples into templates

### ISSUE THREAD

**Issue by tbielawa** [ManageIQ/manageiq-pods#222]
In https://github.com/openshift/openshift-ansible/pull/5336 I converted the server and the postgres db PVs into templates with parameters to make it easier and more natural to use with the openshift-ansible oc_* tools (process, create, etc).

I create the PV templates in here:
* https://github.com/openshift/openshift-ansible/pull/5336/files#diff-408ea6dc0d53b2060afcab9004f3d1e7

And then later I conditionally create each template in here:
* https://github.com/openshift/openshift-ansible/pull/5336/files#diff-0049ddfb751973936061ec914a7a967eR30
* https://github.com/openshift/openshift-ansible/pull/5336/files#diff-0049ddfb751973936061ec914a7a967eR44 (I realize that has the wrong task `name`, it should say `CFME DB PV`, I'll update it)

Here's the server PV template and the DB template file:

Server Template
* https://github.com/openshift/openshift-ansible/pull/5336/files#diff-3d51858af4ddb5e63305e906ceaf8c20

DB Template
* https://github.com/openshift/openshift-ansible/pull/5336/files#diff-cfe1b5ebff1a423bbd197ee2676a4e0c

Would you consider shipping these updated versions in your repo?

They're a little rough right now, so, if you're open to this then I'll submit a PR and we can get them using language/formatting you prefer.

Thanks!

**Comment by carbonin** [comment]
I'm :+1: on this.

Our PV examples are, well, just examples right now. This would allow someone to create a pv directly using the `oc` tooling without editing the files (and dirtying their local git status).

The only question I would have is around how we do backup and restore. @fbladilo would this change that process at all? In particular I'm concerned about the hard-coded values for things like the backup pvc, would we also want to template that as a part of this change to be consistent?

**Comment by carbonin** [comment]
Still would want @bdunne and @fbladilo to comment on this about the general direction. You guys have anything to add?

**Comment by tbielawa** [comment]
Some more information

What I did with the example templates you provide was fairly limited:

* I changed it to the kube `template` form, which means the **FIRST** `kind` tag in the inventory is with value `template`, then some labels, annots, etc. Then there's a `objects` section. Basically cut the old PV definitions and indent them as a list. You know, like how the miq-template.yaml and miq-template-ext-db.yaml files are now.

* I added a `parameters` key after the list of objects in the `objects` top-level-key. I replaced variable-value field values with variables. 

I know that might sound confusing. So for example:

```yaml
    capacity:                                                                                                                                                                                                        
      storage: 15Gi                                                                                                                                                                                       
```

Becomes 

```yaml
    capacity:
      storage: "${DB_PV_SIZE}"
# ...
parameters:
- name: DB_PV_SIZE
  displayName: PV Size for App DB
  required: true
  description: The size of the MIQ DB PV given in Gi
  value: 15Gi
```

How to process these? During experimentation/study I figured out that this works:

1. Copy (`scp`?) your template to your OC cluster
1. `oc create -f /path/to/template.yaml` - now it's in the system. You can reference it by name when using `oc process` later on
1. `oc process <name-of-template> -p NFS_HOST=nfs.example.com DB_PV_SIZE=15Gi BASE_PATH=/exports | oc create -f -` You created the thingies the the thing!

**Comment by tbielawa** [comment]
@bdunne @fbladilo @carbonin Any more thoughts on this?

**Comment by carbonin** [comment]
I think @bdunne is traveling this week so I would give him some time to respond.

@fbladilo has no excuse :stuck_out_tongue_winking_eye:

**Comment by tbielawa** [comment]
PR sent w/ questions for discussion.

**Comment by fbladilo** [comment]
@tbielawa @carbonin 😄 Sorry been busy with some ansible training thingies... will check on PR.
