### ISSUE TITLE
setting MIQ admin password during installation / template processing

### ISSUE THREAD

**Issue by joelddiaz** [ManageIQ/manageiq-pods#237]
Currently when using the OpenShift templates to install MIQ, there is no way to set the MIQ admin password. The MIQ pod comes up with a publicly accessible OpenShift route with the default creds.

Need a way to set the admin MIQ password before the pod is publicly accessible.

Opened a similar issue out on openshift/openshift-ansible#5849 and it was recommended I open this issue here.

**Comment by moolitayer** [comment]
@gtanzillo this seems like a major flaw? I'm thinking the solution should be limited to production env? 

@joelddiaz What's the usual approach for something like this? Generating a random pass and storing it in a file an admin can access? providing an optional password during installation (`oc new-app --template=manageiq -p PASSWORD=<password>`)?

@miq-bot assign @gtanzillo

**Comment by gtanzillo** [comment]
@fbladilo Can you take a  shot at addressing this issue. We were think ing that we could parameterize the admin password in the template.

**Comment by joelddiaz** [comment]
@moolitayer i would prefer a system where i can pass the desired password and have it applied during installation

**Comment by fbladilo** [comment]
@gtanzillo For sure, I can take it , will post something later today.

**Comment by carbonin** [comment]
Closing as https://github.com/ManageIQ/manageiq-pods/pull/250 is merged
