### ISSUE TITLE
Need to be able to configure to bypass the posgres version validity check

### ISSUE THREAD

**Issue by bazulay** [ManageIQ/manageiq-pods#247]
related to: https://github.com/ManageIQ/manageiq/issues/16486

Need a way to  configure out the postgres version check using the template.

@gtanzillo  I think additional issue is required to expose it in the ansible installer.

**Comment by bazulay** [comment]
@miq-bot assign carbonin

**Comment by carbonin** [comment]
> I think additional issue is required to expose it in the ansible installer.

Can you clarify this @bazulay? As I understand it, no changes will be required in this repo.

**Comment by bazulay** [comment]
@carbonin  we have agreed (ManageIQ/manageiq#16486) to have a config parameter to configure out this validation (for postgres 9.5) on production deployment. 
This issue is to expose this config  in the template so when deploying it on OCP one can in advanced disable this validation so the PODified appliance can be deployed using AWS Aurora (which provides postgres 9.6)

**Comment by bazulay** [comment]
@gtanzillo this config probably need to be also exposed in the related ansible role

**Comment by bazulay** [comment]
@carbonin  @gtanzillo  this is a major usability issue, 
@fbladilo  I wonder whether there is a way to pass env variables not through the template parameters ?

**Comment by carbonin** [comment]
> this is a major usability issue,

That's kind of the point. We want unsupported configurations to be difficult to achieve.

> I wonder whether there is a way to pass env variables not through the template parameters

There is, I mentioned the possibilities in my comment. If it were me, I would add the variable to the deployment config's [`env` list](https://github.com/ManageIQ/manageiq-pods/blob/15017389bc86a622538308298f7b20fbc5ca0eee/templates/miq-template-ext-db.yaml#L196) before deploying the app from the template.

**Comment by carbonin** [comment]
I'll test this out today and close the issue when I can confirm it works.

**Comment by carbonin** [comment]
Editing the deployment config to include the following will allow PG 9.6 to be used with the application.

```
- name: UNSAFE_PG_VERSION
  value: 1
```

Closing this.
