### ISSUE TITLE
openshift jobs cannot be re-run

### ISSUE THREAD

**Issue by izapolsk** [ManageIQ/manageiq-pods#285]
Usually users schedule database backup. However, paragraph regarding database backup/restore doesn't mention that openshift jobs can be run only once and old job should be removed before next run.
So, I believe there should be apropriate note regarding openshift jobs.

**Comment by carbonin** [comment]
Do you think a note is good enough or should be just move it from a `Job` to a `CronJob` so it will run as a schedule if that's the more common use case?

**Comment by izapolsk** [comment]
From my point CronJob would be even better. Backups are usually scheduled and they  are rarely done in ad-hoc manner
