### ISSUE TITLE
restore db job doesn't show which backup is used

### ISSUE THREAD

**Issue by izapolsk** [ManageIQ/manageiq-pods#286]

**Comment by carbonin** [comment]
Is this just a request to print the file used to the logs?

The README mentions which file will be used and how to specify a particular file:

>The latest successful DB backup will be restored by default, this can be adjusted via the BACKUP_VERSION environment variable on restore object template

**Comment by izapolsk** [comment]
yes, this request. it would be good to know what snapshot it is using to restore db.
