### ISSUE TITLE
Problem when change apache httpd Service Name - gaprindashvili

### ISSUE THREAD

**Issue by alexey-ban** [ManageIQ/manageiq-pods#299]
Problem when change apache httpd Service Name - Service without pod and route for httpd does not work

In miq-template.yaml, strings 788 and 802
    selector:
      name: httpd

I think would be better 
    selector:
      name: "${HTTPD_SERVICE_NAME}"

**Comment by carbonin** [comment]
@alexey-ban actually I've debated removing the parameters for things like service names entirely.

What was your use case for changing the service name? Curious if I should just hardcode `httpd` or fix the places that don't currently use the parameter as a fix for this.

**Comment by alexey-ban** [comment]
Hi @carbonin.

I change service name because I want create 2 region (master-slave) miq in 1 openshift project

**Comment by carbonin** [comment]
So we went the direction of hard-coding the service name. If you want to deploy multiple instances of the application it will have to be in different namespaces.
