### ISSUE TITLE
PostgreSQL pod fails to start

### ISSUE THREAD

**Issue by BostjanBozic** [ManageIQ/manageiq-pods#346]
Hello,

Version:
* openshift v3.11.0+bd0bee4-337

I am experiencing issue deploying ManageIQ (`ivanchuk` release) due to PostgreSQL issues (using PV to deploy PostgreSQL). When deployed, PostgreSQL pod fails with following:
```
waiting for server to start....2019-11-12 12:06:50 UTC::5dcaa05a.19:@:[25]:FATAL:  could not access file "pglogical": No such file or directory
2019-11-12 12:06:50 UTC::5dcaa05a.19:@:[25]:LOG:  database system is shut down
stopped waiting
pg_ctl: could not start server
Examine the log output.
```

Same issue occurs if using `hammer` release. What I saw is that if you change using PostgreSQL tag from `latest` to `9.5` (only on `hammer` release, as `ivanchuk` requires PostgreSQL v10.0 or above), ManageIQ is normally deployed.

Is there any way to disable `pglogical` request - if I understood correctly, this is in any case no longer required (https://github.com/ManageIQ/manageiq-pods/pull/336)?

Thank you and best regards,
Bostjan

**Comment by carbonin** [comment]
You can remove `pglogical` from the `shared_preload_libraries` list in the postgresql config map [here](https://github.com/ManageIQ/manageiq-pods/blob/ivanchuk/templates/miq-template.yaml#L91). That should solve the issue. And since we moved to PG 10 for the ivanchuk release, could you open a patch to the `ivanchuk` branch for this change as well?

**Comment by BostjanBozic** [comment]
Cheers for reply!

It seems that whole line `shared_preload_libraries = 'pglogical,repmgr'` needs to be deleted - no idea if this has any additional implications, but for now this seems to do the trick.

I actually never opened any PR or patch before. I presume you simply mean a PR toward `ivanchuk` branch?

**Comment by carbonin** [comment]
> I presume you simply mean a PR toward ivanchuk branch?

Yup, that would do it.

**Comment by BostjanBozic** [comment]
Ok, will do it. Thank you again for help.
