### ISSUE TITLE
Allow use of private GitHub/GitLab

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-pods#358]
- need to parameterize the images builds to change
  - https://github.com -> $GITHUB_HOST
  - manageiq- prefix -> $REPO_PREFIX
  - ability to fetch a token from host.docker.internal or something
    - $FETCH_TOKEN would drive whether or not to fetch the token, and the token would be stored in a different ENV var

**Comment by Fryguy** [comment]
FYI @carbonin

**Comment by carbonin** [comment]
Closed via #362
