### ISSUE TITLE
MIQ_ORG, SUI_ORG, APPLIANCE_ORG should default to MIQ_ORG

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-pods#359]
It's unlikely that all 3 won't be the same, so perhaps it's better to set, for example, `SUI_ORG=${SUI_ORG:-$MIQ_ORG}`

**Comment by carbonin** [comment]
I was thinking of the developer use case here. Where you want to build with your fork of MIQ, but don't want to keep your fork of the others up to date.

**Comment by Fryguy** [comment]
Oh, we should definitely still allow overriding individual ones, but IMO they should default to MIQ_ORG instead of deafaulting to "ManageIQ"

**Comment by carbonin** [comment]
I think the problem then is that if you want to override one you need to override all of them. So if I want to build the images for the miq code in my fork I have to do `MIQ_ORG=carbonin SUI_ORG=ManageIQ APPLIANCE_ORG=ManageIQ` where previously I just had to specify MIQ_ORG.

Or am I misunderstanding the request?

**Comment by Fryguy** [comment]
No, that's fair... I didn't see that option.  I guess your version is a bigger use case (developer changing a fork), so I'll close this one.
