### ISSUE TITLE
Allow for productization of image builds

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-pods#360]
This is possibly done by insert the following lines in the manageiq-base Dockerfile after curling the 3 repos...maybe 😝 

```
ENV PRODUCTIZATION_ROOT=/opt/manageiq/miq_productization
RUN mkdir -p ${PRODUCTIZATION_ROOT} && \
    curl -L https://github.com/${PRODUCTIZATION_ORG}/miq_productization/tarball/${PRODUCTUZATION_REF} | tar vxz -C ${PRODUCTIZATION_ROOT} --strip 1
RUN cd ${PRODUCTIZATION_ROOT} && \
    ./link.rb
```

**Comment by Fryguy** [comment]
Part of productization also includes changing the product name.  However, product name is coupled to the name of the objects being deployed [1], which causes issues, since the template and the generated names don't match.  We should avoid coupling those 2 things, by introducing an ENV var, such as PRODUCT_PREFIX, which would be used as the prefix instead hardcoding [2] or relying on the product name [3].

[1] https://github.com/ManageIQ/manageiq/blob/master/lib/container_orchestrator/object_definition.rb#L91-L93
[2] https://github.com/ManageIQ/manageiq/blob/master/lib/container_orchestrator/object_definition.rb#L17
[3] https://github.com/ManageIQ/manageiq/blob/master/lib/container_orchestrator/object_definition.rb#L75

cc @carbonin

**Comment by carbonin** [comment]
@Fryguy So I can implement what you put in the first comment if we create a `https://github.com/ManageIQ/miq_productization` repo with a no-op `link` scrip for now (thinking `/bin/true`). Then anyone who wants can fork that repo and commit whatever they want.

**Comment by Fryguy** [comment]
Oh, like, for example purposes?  Or you literally want to clone that repo?  I was thinking it would be ENV var driven, and in the abscense of the ENV var we wouldn't clone anything.

**Comment by chessbyte** [comment]
@carbonin @Fryguy let's keep this discussion moving forward, as I would like this to make it into the early timeframe of the Jansa release (beta)
