### ISSUE TITLE
Cant see “configure” option on Openshift origin when selecting items

### ISSUE THREAD

**Issue by uselessidbr** [ManageIQ/manageiq-pods#373]
I just installed manageiq on openshift origin but whenever i select an item (lets say a Container provider) it doesnt have a “configure” toolbar/button that lets me, for example, delete the provider.

Theres no toolbar at the UI at all!

What did i miss?

**Comment by uselessidbr** [comment]
Its related to the browser. As i had only one browser installed (edge) which has this behaviour i then downloaded a portable version of firefox which presented the toolbar correctly.

**Comment by carbonin** [comment]
Glad to see you resolved the issue
