### ISSUE TITLE
Openscap scanner not working

### ISSUE THREAD

**Issue by uselessidbr** [ManageIQ/manageiq-pods#374]
While scanning container Images openscap doesnt show any results neither a report. Im not sure which pod is in charge of run the scanner but it seems that something is missing here.

Any thoughts?

Thanks!

**Comment by chessbyte** [comment]
@simon3z do we have any documentation on this?

**Comment by carbonin** [comment]
@uselessidbr is this something that works for you on the VM appliance?

**Comment by carbonin** [comment]
Wondering if this could be related to https://github.com/ManageIQ/manageiq/issues/19957

**Comment by simon3z** [comment]
The pods scanning the image are `manageiq-img-scan-*`. See:

https://github.com/ManageIQ/manageiq-providers-kubernetes/blob/master/app/models/manageiq/providers/kubernetes/container_manager/scanning/job.rb
https://github.com/ManageIQ/manageiq-providers-kubernetes/blob/master/config/settings.yml

cc @chessbyte @oourfali

**Comment by carbonin** [comment]
I was able to get this to work with the latest pods master. @uselessidbr can you share what you did or any specific errors you encountered?

The scan I ran didn't finish with a SCAP report (as there's no targets for UBI, I believe), but it did successfully list the packages in the image as can be seen in this screenshot:

![image](https://user-images.githubusercontent.com/12697904/77681561-e1480a00-6f6b-11ea-8c6e-053a2f346f77.png)

Additionally you should be able to see the task status:

![image](https://user-images.githubusercontent.com/12697904/77681631-03da2300-6f6c-11ea-80ce-64c93cc97159.png)

**Comment by carbonin** [comment]
The process seems to require a particular service account (`inspector-admin`) to exist in the `management-infra` namespace. I also believe the namespace used is configurable.

**Comment by uselessidbr** [comment]
Sorry @carbonin didn't have the time to test it. I will try with the latest version and let you know. Thanks for your help!

**Comment by uselessidbr** [comment]
> I was able to get this to work with the latest pods master. @uselessidbr can you share what you did or any specific errors you encountered?
> 
> The scan I ran didn't finish with a SCAP report (as there's no targets for UBI, I believe), but it did successfully list the packages in the image as can be seen in this screenshot:
> 
> ![image](https://user-images.githubusercontent.com/12697904/77681561-e1480a00-6f6b-11ea-8c6e-053a2f346f77.png)
> 
> Additionally you should be able to see the task status:
> 
> ![image](https://user-images.githubusercontent.com/12697904/77681631-03da2300-6f6c-11ea-80ce-64c93cc97159.png)

Basically it is the issue i get. It doesn't output any report. Does creating the SA solve this issue?

**Comment by carbonin** [comment]
No I think that's a SCAP configuration issue. The report it generates is based on the operating system (or in this case container image) so if there is no configuration available for the system you're scanning then you won't get a SCAP report back.

My point here is that scanning is working, but just the SCAP piece might have a problem for particular container images.

I would say this is only an issue for this repository if you're getting different results with the appliance. If you're seeing the same results with both the appliance and the container versions of ManageIQ then I would open an issue in either the [manageiq-smartstate](https://github.com/ManageIQ/manageiq-smartstate) or [manageiq-providers-openshift](https://github.com/ManageIQ/manageiq-providers-openshift) repo

cc @agrare

**Comment by agrare** [comment]
According to https://access.redhat.com/documentation/en-us/reference_architectures/2018/html/managing_large-scale_openshift_installations_with_cloudforms_4.6/smartstate_analysis#identifying_smartstate_analysis_problems (sorry couldn't find upstream docs for openshift ssa)

> 8.3.1.4. Non-RHEL Images
> If the container image is based on a non-RHEL operating system, the image-inspector container writes the following message:
> ```
> Unable to run OpenSCAP: Unable to get RHEL distribution number: could not find RHEL dist
> ```

**Comment by agrare** [comment]
So, doesn't sound like an issue unless you're using RHEL based images

**Comment by uselessidbr** [comment]
> So, doesn't sound like an issue unless you're using RHEL based images

So i presume it won't generate a report for containers using centos/fedora images. Is that it?

**Comment by uselessidbr** [comment]
> > So, doesn't sound like an issue unless you're using RHEL based images
> 
> So i presume it won't generate a report for containers using centos/fedora images. Is that it?

Looking at the doc it seems to work only with RHEL images. That's a shame :(
