### ISSUE TITLE
Discussion for using ibm-ci-bot to manage this repo

### ISSUE THREAD

**Issue by gyliu513** [ManageIQ/manageiq-pods#391]
Here is a chart for ibm prow https://github.com/gyliu513/roadmap/issues/9#issue-571136639 

![image](https://user-images.githubusercontent.com/4461983/77444595-04b56c80-6e27-11ea-8551-b9a7e42f013f.png)

So with above model, we can enable multi-arch build for manageiq operator.

Some reference:
- ibm-ci-bot account https://github.com/ibm-ci-bot
- IBM Prow repo https://github.com/ibm/test-infra

FYI @Fryguy @chessbyte

**Comment by Fryguy** [comment]
Unless ibm prow is hosted publicly, I think we won't do this.  We can revisit in the future perhaps running a MIQ specific prow.
