### ISSUE TITLE
Build operator directly in the Dockerfile

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-pods#403]
Originally raised in https://github.com/ManageIQ/manageiq-pods/pull/389#discussion_r397314395

------------------------------------------------------

I'm not sure this is really the way to go. We could integrate `operator-sdk build docker.io/manageiq/manageiq-operator:latest` into `bin/build`

**Comment by mali-chainzee** [comment]
btw, where do you plan to release the operator at the end? because if we release via registry.redhat.io, all the deps for build will eventually have to be committed to dist-git repo.

**Comment by Fryguy** [comment]
Ultimately I'd expect the operator on operatorhub.io (#415)

**Comment by carbonin** [comment]
I think this is probably not a great idea. I think we can continue to use `operator-sdk build` for this.
