### ISSUE TITLE
Can we productize the CR kind name?

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-pods#410]

**Comment by sethpeterson** [comment]
Leaving the relevant operator sdk command here:
```
operator-sdk xxx --api-version=<Your Component>.groupname.com/v1alpha1 --kind=<Your Kind>
```

**Comment by carbonin** [comment]
@sethpeterson I don't see those options in `operator-sdk` v0.9.0. Do you know if they were added in a specific version?

**Comment by sethpeterson** [comment]
@carbonin This is operator-sdk 0.15.1
```
operator-sdk new --help | grep api-version
--api-version string          Kubernetes apiVersion and has a format of $GROUP_NAME/$VERSION (e.g app.example.com/v1alpha1) - used with "ansible" or "helm" types
```

I haven't found where it was added but I see reference to changes to the api-version flag in the 0.8.0 release notes

**Comment by carbonin** [comment]
Right, that's `operator-sdk new` ... That's what we would run if we were building an entirely new operator application. Your comment made it seem like we could pass a new kind to `operator-sdk build` or some other command.

Also, for what it's worth, I have serious doubts that dropping the existing code here into a scaffold built with a much newer sdk version will work correctly (if that was what you were thinking).

**Comment by sethpeterson** [comment]
From what I have seen, you are correct that changing operator-sdk version will matter a lot here.  Is the plan to stick with 0.8.0?

**Comment by carbonin** [comment]
Right now we're using `0.9.0`. I would like to upgrade, but I'm still trying to figure out what the priority of that is. We're tracking the upgrade in https://github.com/ManageIQ/manageiq-pods/issues/405

**Comment by gyliu513** [comment]
It seems we need to re-generate the code if want to change the kind based on comments here https://github.com/operator-framework/operator-sdk/issues/2819#issuecomment-612639233

**Comment by carbonin** [comment]
Okay, so it looks like the answer here is just "no". It will require a code change. Closing this one.
