### ISSUE TITLE
Add kafka deployment to operator

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-pods#411]

**Comment by carbonin** [comment]
This is making me think more about how we handle secrets in the operator. Right now we're asking the user to put their passwords in the CR in plaintext with no option to generate one for them.

I've seen some examples of operators that ask for the names of secrets that would have to be managed separately. Does that make more sense? What do you think @Fryguy ?

We could also have some in-between option where we generate a secret object if one wasn't passed. As far as I can tell there's no handling of default values right now. I think the user needs to provide every one of the parameters in the CR.

Also allowing the user to specify a pre-created secret will also solve our bring-your-own TLS cert problem (https://github.com/ManageIQ/manageiq-pods/issues/409)

**Comment by carbonin** [comment]
@gyliu513 Maybe you can offer some ideas with respect to best practices for this sort of thing?

**Comment by Fryguy** [comment]
I agree, I don't like secrets plaintext in a CR...that just feels wrong.  I would rather that referred to an actual secret.  I've seen vault extensions to kubernetes where you ask kubernetes for a secret and it, in turn, talks to a vault, so that would automatically open up vault support for this stuff.

**Comment by gyliu513** [comment]
@carbonin @Fryguy +1 for this as well.

According to Kubernetes official doc: https://kubernetes.io/docs/concepts/configuration/secret/

Kubernetes Secrets let you store and manage sensitive information, such as passwords, OAuth tokens, and ssh keys. Storing confidential information in a Secret is safer and more flexible than putting it verbatim in a Pod definition or in a container image.

Secret Design Doc: https://git.k8s.io/community/contributors/design-proposals/auth/secrets.md

According to: https://blog.aquasec.com/managing-kubernetes-secrets Placing sensitive info into a secret object does not automatically make it secure. By default, data in Kubernetes secrets is stored in Base64 encoding, which is practically the same as plaintext.

However, secrets give you more control over access and usage of passwords, keys, etc. Kubernetes can either mount secrets separately from the pods that use them, or save them as environment variables.

We also fixed a similiar issue in IBM projects at https://github.com/ibm/ibm-mongodb-operator/issues/67
