### ISSUE TITLE
httpd config maps are not created correctly

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-pods#427]
When running the operator from the command line (haven't tested running from inside the cluster yet), the httpd config maps are empty. This prevents the httpd pod from routing requests correctly.

![image](https://user-images.githubusercontent.com/12697904/78714838-7f33c100-78ea-11ea-97ca-4a5e629175dd.png)

Specifically this is currently the landing page:

![image](https://user-images.githubusercontent.com/12697904/78715910-0f263a80-78ec-11ea-9238-3061357b28b1.png)

**Comment by mali-chainzee** [comment]
This is because the paths of the config files have been changed, likely because I forgot to switch folder name "resource" to "helpers" in the code. fixing it with another commit now

**Comment by carbonin** [comment]
Fixed by https://github.com/ManageIQ/manageiq-pods/pull/437
