### ISSUE TITLE
Removing a manageiq CR leaves the worker containers

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-pods#428]
Removing the application using the operator deletes all the resources it created, but doesn't let the orchestrator come down cleanly.

This leaves all the worker deployment that the orchestrator created running.

It's possible that I "broke" this with https://github.com/ManageIQ/manageiq-pods/pull/420/commits/94a49f97255debf6b8c0107b6f7a464e3886298c, but we really should be letting the orchestrator come down cleanly.

**Comment by mali-chainzee** [comment]
There was function to clean up the worker pods with label selector in my first PR, it seems to have been removed in one of the later commits

**Comment by carbonin** [comment]
Yup I referenced that in the issue description, but I think it was the wrong approach as I would prefer the orchestrator be able to take down the deployments cleanly rather than the operator removing resources that it doesn't manage.

**Comment by mali-chainzee** [comment]
Worker pods will be removed cleanly if you set the orchestrator deployments as the owner of the worker pods when creating them with k8s api.

**Comment by carbonin** [comment]
There's application logic that is built into taking the pods down that I want to preserve. I'd rather not just let kubernetes handle it.

**Comment by carbonin** [comment]
Maybe we could have both. In this case I guess we're removing everything anyway so there's no reason to let everything come down cleanly. We could still keep the logic that lets the orchestrator remove the worker deployments when it is scaled down...
