### ISSUE TITLE
Build failures on ppc64le

### ISSUE THREAD

**Issue by seth-priya** [ManageIQ/manageiq-pods#460]
@miq-bot add_label bug

**What steps did you take and what happened:**
Building the docker images using ./bin/build -d images -r manageiq

Build failed at different points with the following errors
1] No match for argument: wmi
Error: Unable to find a match: wmi
The command '/bin/sh -c dnf -y --disableplugin=subscription-manager install http://mirror.centos.org/centos/8/BaseOS/${ARCH}/os/Packages/centos-repos-8.1-1.1911.0.8.el8.${ARCH}.rpm http://mirror.centos.org/centos/8/BaseOS/${ARCH}/os/Packages/centos-gpg-keys-8.1-1.1911.0.8.el8.noarch.rpm https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm &&     dnf -y --disableplugin=subscription-manager module enable nodejs:12 &&     dnf -y --disableplugin=subscription-manager module enable ruby:2.6 &&     dnf -y --disableplugin=subscription-manager --setopt=tsflags=nodocs install       ansible                           ansible-runner                    cmake                             cockpit-ws                        cockpit-ssh                       cyrus-sasl                        cyrus-sasl-plain                  file                              freeipmi                          gcc-c++                           git                               glibc-langpack-en                 hostname                          http-parser                       ipmitool                          iproute                           libcurl-devel                     libpq                             libssh2-devel                     libtool                           libxml2-devel                     libxslt-devel                     logrotate                         lvm2                              make                              net-snmp                          net-snmp-libs                     net-snmp-utils                    nmap-ncat                         nodejs                            openldap-clients                  openscap-scanner                  openssl-devel                     OpenIPMI                          patch                             postfix                           postgresql-devel                  procps-ng                         python3-devel                     qpid-proton-c-devel               redhat-rpm-config                 ruby-devel                        socat                             sqlite-devel                      v2v-conversion-host-ansible       wget                              wmi                               xz                                &&                              dnf clean all' returned a non-zero code: 1

2] Installing unf_ext 0.0.7.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/share/gems/gems/unf_ext-0.0.7.2/ext/unf_ext
/usr/bin/ruby -I /usr/share/rubygems -r ./siteconf20200421-3381-5495f2.rb
extconf.rb
checking for -lstdc++... yes
creating Makefile

current directory: /usr/share/gems/gems/unf_ext-0.0.7.2/ext/unf_ext
make "DESTDIR=" clean
rm -f
rm -f unf_ext.so  *.o  *.bak mkmf.log .*.time

current directory: /usr/share/gems/gems/unf_ext-0.0.7.2/ext/unf_ext
make "DESTDIR="
g++ -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.   -fPIC
-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2
-Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong
-grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1
-specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mcpu=power8 -mtune=power8
-funwind-tables -fstack-clash-protection -m64 -o unf.o -c unf.cc
In file included from unf/normalizer.hh:10,
                 from unf.cc:1:
unf/table.hh:13539:25: error: narrowing conversion of ‘-27’ from ‘int’ to ‘char’
inside { } [-Wnarrowing]
  -77, -39,-124, -39,-123};
                         ^
unf/table.hh:13539:25: error: narrowing conversion of ‘-113’ from ‘int’ to
‘char’ inside { } [-Wnarrowing]

3] gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/share/gems/bundler/gems/manageiq-ui-classic-81b5f2aa236f/node_modules/node-sass/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/share/gems/bundler/gems/manageiq-ui-classic-81b5f2aa236f/node_modules/node-sass/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/share/gems/bundler/gems/manageiq-ui-classic-81b5f2aa236f/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/share/gems/bundler/gems/manageiq-ui-classic-81b5f2aa236f/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/share/gems/bundler/gems/manageiq-ui-classic-81b5f2aa236f/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/share/gems/bundler/gems/manageiq-ui-classic-81b5f2aa236f/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/share/gems/bundler/gems/manageiq-ui-classic-81b5f2aa236f/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:166:21)
gyp ERR! System Linux 3.10.0-1062.12.1.el7.ppc64le
gyp ERR! command "/usr/bin/node" "/usr/share/gems/bundler/gems/manageiq-ui-classic-81b5f2aa236f/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/share/gems/bundler/gems/manageiq-ui-classic-81b5f2aa236f/node_modules/node-sass
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1

**What did you expect to happen:**
All images are built successfully

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
uname -a
Linux p006n04 3.10.0-1062.12.1.el7.ppc64le #1 SMP Thu Dec 12 11:47:54 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux
docker --version
Docker version 18.06.3-ce, build d7080c1

- ManageIQ version: master
- Minikube/KIND/OCP version: None
- Kubernetes version: (use `kubectl version`): None
- OS (e.g. from `/etc/os-release`):
cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"

**Comment by seth-priya** [comment]
On 2] the issue seems to be with the unf_ext gem and this seems to "workaround" the issue
diff --git a/images/manageiq-base/Dockerfile b/images/manageiq-base/Dockerfile
index 757706f..3f21b18 100644
--- a/images/manageiq-base/Dockerfile
+++ b/images/manageiq-base/Dockerfile
-    if [ ${ARCH} = "ppc64le" ] ; then gem install sassc  -- --disable-march-tune-native ; fi && \
+    if [ ${ARCH} = "ppc64le" ] ; then gem install sassc  -- --disable-march-tune-native && gem install unf_ext -v '0.0.7.2' -- --with-cxxflags="-fsigned-char"; fi && \

On 3] this seems to do the trick
--- a/images/manageiq-ui-worker/Dockerfile
+++ b/images/manageiq-ui-worker/Dockerfile
@@ -10,7 +10,7 @@ LABEL name="manageiq-ui-worker" \
       summary="ManageIQ user interface worker image"

 # Install httpd and remove the existing httpd config from manageiq-appliance
-RUN dnf -y --disableplugin=subscription-manager --setopt=tsflags=nodocs install httpd && \
+RUN dnf -y --disableplugin=subscription-manager --setopt=tsflags=nodocs install httpd python2 && \

**Comment by seth-priya** [comment]
I was able to build all the images after working around these three issues (disabled wmi install for 1])

**Comment by Siddhesh-Ghadi** [comment]
The **unf_ext** gem installation issue is also seen while building **manageiq** on power with same failure. The reason for this is the default behavior of **char type** on power which is **unsigned** and leads to the failure of conversion of negative integer to char. 
*Unf_ext issues related to this*
>https://github.com/knu/ruby-unf_ext/issues/15
https://github.com/knu/ruby-unf_ext/issues/26

Added a bundler configuration in [tools/ci/setup_ruby_env.sh](https://github.com/Siddhesh-Ghadi/manageiq-/blob/e431dee0fad0d07258feb7dfe5bd77ace5c655df/tools/ci/setup_ruby_env.sh#L4) to fix this
```
bundle config --local build.unf_ext --with-cxxflags=-fsigned-char
```

**Comment by simaishi** [comment]
> On 1], the wmi RPM seems to coming from https://copr-be.cloud.fedoraproject.org/results/manageiq/ManageIQ-Master/epel-8-x86_64/01173723-wmi/
> 
> while the same is not present for ppc64le
> https://copr-be.cloud.fedoraproject.org/results/manageiq/ManageIQ-Master/epel-8-ppc64le/
> 
> @simaishi your guidance here?

Copr is going through infrastructure migration and ppc64le chroot was deactivated. Because of that, I will not be able to build any ppc64le rpms right now. I will take a look when ppc64le environment is back in Copr. As per copr outage announcement, it might not come back until June.

**Comment by seth-priya** [comment]
@simaishi thank you for your response! Could you please help me understand what is wmi used for in this context- the build proceeds without it, but I believe it may be needed at run time? what would be the impact here? also maybe we can consider building it from source in the dockerfile as a short term alternative? which repo would this be, is it https://github.com/tjguk/wmi ? I can give it a try in my local environment ..

**Comment by simaishi** [comment]
@seth-priya It is for run time, for Windows VMs, but I'm not sure exactly what you can't do without it... hopefully @carbonin can answer that question.

The source RPM can be found in Copr: https://copr-be.cloud.fedoraproject.org/results/manageiq/ManageIQ-Master/epel-8-x86_64/01173723-wmi/wmi-1.3.14-2.el8.src.rpm, so that can probably be used if you're going to try building the RPM.

**Comment by simaishi** [comment]
In regards to issue 3 about 'python', in the last few days I ran multiple builds on x86_64, I saw that error once.  All other times, the builds have been successful.  I'm not sure if you see that error every time or not. But either way, we should investigate this before adding python2 package.

Hoping @himdel can help out...

**Comment by seth-priya** [comment]
@simaishi thanks for the pointers - the python error is consistent for me, I will look at building wmi from source

**Comment by carbonin** [comment]
Regarding `wmi`: [this](https://github.com/ManageIQ/manageiq/blob/468521a8d3b892678f106e1d5e5ee1cdbade4490/app/models/vm.rb#L88) is the only reference I could find which looks like it's querying for the running processes on a windows VM.

**Comment by himdel** [comment]
According to https://github.com/nodejs/node-gyp/issues/1687#issuecomment-541471076,
as of node-gyp 5.0.5+ and 6.0.0+, python3 is supported.

Which means any npm packages which need to build node binary bindings must depend on those versions to work, and anything depending on older node-gyp will fail without python being python 2.

(Not yet sure about the specific packages and versions we're using.)

**Comment by seth-priya** [comment]
so @carbonin does it make sense to completely skip the wmi installation for ppc64le? thoughts?

**Comment by carbonin** [comment]
I think it still needs to be there as it's in the Gemfile. I'd be surprised if the app started up if it wasn't installed.

**Comment by simaishi** [comment]
wmi is a RPM, so I'd think it's fine to skip it?  It was never included in pods until @carbonin added it a few months ago.

**Comment by carbonin** [comment]
Ah, right. I was thinking a gem. As long as the build finishes then yeah, we can skip for now.

**Comment by seth-priya** [comment]
yes, the build does finish fine without wmi …

**Comment by carbonin** [comment]
So yeah, we're exposing ourselves to a bug where we won't be able to list processes on windows machines, but if that's blocking the ppc64le build then it feels like an acceptable risk.

**Comment by simaishi** [comment]
@himdel looked into changing version constraint on ui-classic to avoid node python issue. But we're out of luck until a new version of node-sass with python 3 support gets released.

It seems it works for me, because there is prebuilt binary for x86_64 and it tries to use it first. The one time I saw the error, it must have failed downloading it and tried to compile.

So, for now, the only option is to add python2, it seems.

**Comment by seth-priya** [comment]
thanks for confirming - I will work on implementing and validating the changes and get back.
