### ISSUE TITLE
Image tag not propagating to worker pods

### ISSUE THREAD

**Issue by bennett-white** [ManageIQ/manageiq-pods#464]
@miq-bot add_label bug

Installed using deploy script in jansa branch

**What did you expect to happen:**
Expected worker pods to have the same image tag as orchestrator pod (latest-jansa) in this example. 

**Environment:**

- Minikube/KIND/OCP version: OCP 4.2
- Kubernetes version: (use `kubectl version`): 1.14

**Comment by carbonin** [comment]
Will be fixed by https://github.com/ManageIQ/manageiq-pods/pull/465 and https://github.com/ManageIQ/manageiq/pull/20094

**Comment by Fryguy** [comment]
Fixed in #465
