### ISSUE TITLE
Orchestrator image pull secret missing from operator

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-pods#472]
**Describe the solution you'd like**
Add an optional image pull secret to the operator to be used for pulling the orchestrator image and provided to the orchestrator to add to the worker deployments.

**Anything else you would like to add:**
Template implementation references:

https://github.com/ManageIQ/manageiq-pods/blob/7787a6a08dab63b06f8b7f20e80362bdba946e41/templates/app/orchestrator.yaml#L83-L84
https://github.com/ManageIQ/manageiq-pods/blob/7787a6a08dab63b06f8b7f20e80362bdba946e41/templates/app/orchestrator.yaml#L118-L119

**Comment by Fryguy** [comment]
Does this also need to propagate like the tag name?

**Comment by carbonin** [comment]
It already does.https://github.com/ManageIQ/manageiq/blob/eca97f587617c57b9043da6d0a0c1791fa22cce8/lib/container_orchestrator/object_definition.rb#L18
