### ISSUE TITLE
ps command was lost in httpd container

### ISSUE THREAD

**Issue by gyliu513** [ManageIQ/manageiq-pods#480]
@miq-bot add_label bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```console
[root@gyliu-ocp-1-inf deploy]# oc exec httpd-579bfdf9d5-dn4lz -- ps -eaf
time="2020-05-02T05:04:22Z" level=error msg="exec failed: container_linux.go:349: starting container process caused \"exec: \\\"ps\\\": executable file not found in $PATH\""
exec failed: container_linux.go:349: starting container process caused "exec: \"ps\": executable file not found in $PATH"
command terminated with exit code 1
```

I recalled I can use `ps` to check the process in httpd container.

FYI @carbonin @Fryguy @chessbyte 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- ManageIQ version:
- Minikube/KIND/OCP version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by carbonin** [comment]
@miq-bot move_issue manageiq/container-httpd
