### ISSUE TITLE
Enable customer can set storageclass in CR

### ISSUE THREAD

**Issue by gyliu513** [ManageIQ/manageiq-pods#488]
@miq-bot add_label bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

If I do not have a default storageclass, then some pods like kafka, postgres etc will keeps pending due to pvc cannot be created.

```console
oc describe pvc kafka-data
Name:          kafka-data
Namespace:     bluecf
StorageClass:
Status:        Pending
Volume:
Labels:        app=inframgmtinstall
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    kafka-7655bb6865-697qt
Events:
  Type    Reason         Age                 From                         Message
  ----    ------         ----                ----                         -------
  Normal  FailedBinding  8s (x13 over 3m2s)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```

**What did you expect to happen:**

it is better to introduce some new fields for those pvcs so that customer can set storageclass manually if there is no default storageclass.

FYI @carbonin 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- ManageIQ version:
- Minikube/KIND/OCP version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by gyliu513** [comment]
@Fryguy @carbonin seems the `VolumeSource` in Kubernetes does not support `StorageClass` based on API here https://github.com/kubernetes/api/blob/master/core/v1/types.go#L51-L159 , any comments for this?

**Comment by carbonin** [comment]
I don't understand why this would matter. The storage class is a property of the PVC. In this case we would set the storage class on the claim as described in https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1. I'm not sure how a different `VolumeSource` comes into the discussion.

**Comment by gyliu513** [comment]
@carbonin if you check https://github.com/ManageIQ/manageiq-pods/blob/master/manageiq-operator/pkg/helpers/miq-components/kafka.go#L219-L226 , you will see we are using `volumes` in a `pod` spec, and we cannot set `storageclass` in a `volume` spec.

**Comment by carbonin** [comment]
Right, the storage class is not a property of the volume source it's a property of the PVC object. So we would set the class here https://github.com/ManageIQ/manageiq-pods/blob/master/manageiq-operator/pkg/helpers/miq-components/kafka.go#L51-L60

**Comment by gyliu513** [comment]
Ah, I see, thanks @carbonin , can you help assign this to me and I will create a PR soon
