### ISSUE TITLE
Backup and Restore in the Operator

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-pods#489]
We should implement application backup and restore as a part of the operator.
I'm not sure of the best-practices around this kind of thing, but I was thinking a separate controller (with separate CRDs) that would watch for ManageIQBackup/ManageIQRestore objects.
Those would represent either a schedule to backup which we would turn into a CronJob object or a one-off request to restore from a particular backup.

I was also thinking we should go farther than just database backup for this, but that can come as a second pass. For example it would be convenient to store the encryption key with the backup so that a new environment could be created quickly, but that might also be a security concern.

Additionally I would like to be able to utilize this for users who may want to move from the appliance-based deployment to the container-based one so whatever format we choose should be easily created by the appliance (say, a tarball that includes the database backup as well as the encryption key and maybe some other metadata).

I think this would be the last gap between the operator and the templates.

For Backup/Restore using Velero:
- [X] https://github.com/ManageIQ/manageiq-pods/pull/626 Annotate volumes that should be backed up
- [x] https://github.com/ManageIQ/manageiq-pods/pull/619 Allow using a selector to backup a smaller set of only essential resources.

**Comment by Fryguy** [comment]
> a tarball that includes the database backup as well as the encryption key and maybe some other metadata

I believe this is what the current backup from the appliance console does, so it would be really cool if we could enable backup via appliance console, then restore via this new controller

**Comment by carbonin** [comment]
> it would be really cool if we could enable backup via appliance console, then restore via this new controller

Yeah, that's what I was thinking.

**Comment by carbonin** [comment]
Based on the [etcd operator](https://github.com/operator-framework/community-operators/blob/master/community-operators/etcd/0.9.2/etcdoperator.v0.9.2.clusterserviceversion.yaml#L79-L111) it looks like the way to go for this would be to represent a single backup request in as a CR then report on the status of that backup in the CR status field.

Then everything needed to complete the backup should be provided in the CR.

**Comment by carbonin** [comment]
Also of note: when looking at the etcd operator it also looks like they [deploy multiple containers in the operator pod](https://github.com/operator-framework/community-operators/blob/master/community-operators/etcd/0.9.4/etcdoperator.v0.9.4.clusterserviceversion.yaml#L210-L223) to handle different functions like backup and restore. I'm not sure what the utility of that is vs separate controllers in the same operator process, but that's probably worth investigating.

**Comment by bdunne** [comment]
For Backup and restore using Velero:
- [X] https://github.com/ManageIQ/manageiq-pods/pull/626 Annotate volumes that should be backed up
- [ ] https://github.com/ManageIQ/manageiq-pods/pull/619 Allow using a selector to backup a smaller set of only essential resources.

**Comment by bdunne** [comment]
Closing for now since #619 enables backup and restore using Velero
