### ISSUE TITLE
missing middleware tables causing replication configure to fail

### ISSUE THREAD

**Issue by huang-cn** [ManageIQ/manageiq-pods#502]
@miq-bot add_label bug

**What steps did you take and what happened:**
Installed latest (May.14) podified cloudforms, doing multi-region config, using podified as global region.
goto:  Settings -> Replication -> Add Subscription
got `Failed to save subscription` message,
`ERROR: relation "public.middleware_datasources" does not exist`

checked the postgres database in podified env,  the `public.middleware_datasources` table does not exist, actually,  all middleware tables are missing.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- ManageIQ version:
- Minikube/KIND/OCP version:
- Kubernetes version: (use `kubectl version`):
OCP 4.3
- OS (e.g. from `/etc/os-release`):
RHEL 7.7

**Comment by carbonin** [comment]
These tables were removed in https://github.com/ManageIQ/manageiq-schema/pull/157 so they should not exist.

Does the table exist in the region you're trying to subscribe to? Both the remote and global region have to be the same version of ManageIQ for replication to work correctly.

Also this doesn't seem like a pods-specific issue so I'm moving this to the main repo.

@miq-bot move_issue manageiq/manageiq
