### ISSUE TITLE
Users need to be able to provide trusted CA certs for the OIDC server

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-pods#507]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
After configuring the app to authenticate using OIDC running an api query with the JWT token fails.

**What did you expect to happen:**
I expected the call to succeed.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The failure happens because the OIDC server's ssl cert is not trusted. The operator needs to accept a secret containing the trusted CA certs to mount into the httpd pod (specifically at `/etc/pki/ca-trust/source/anchors`)

**Comment by carbonin** [comment]
The other option to to tell mod-auth-oidc to accept an insecure connection to the oidc server.

This would be done by setting the following parameters in the httpd config.
```
OIDCSSLValidateServer Off
OIDCOAuthSSLValidateServer Off
```

I'm not sure what logic we want for this, but I think we have three options:

1. Always require an OIDC user pass the certs secret.
2. Set these to `Off` if everything other than the cert secret is passed (either and entire config in `HttpdAuthConfig` or both `OIDCAuthIntrospectionURL`, `OIDCClientSecret`)
3. Have a separate parameter in the CR for turning these parameters to `Off`

@Fryguy @jvlcek thoughts?

**Comment by Fryguy** [comment]
I like option 2, which I read as, if a cert secret is passed we honor it otherwise we set OIDCSSLValidateServer and OIDCOAuthSSLValidateServer to Off.

**Comment by jvlcek** [comment]
Agreed. If the cert is passed do not include OIDCSSLValidateServer and OIDCOAuthSSLValidateServer

If the cert is not found then set these:

```
OIDCSSLValidateServer Off
OIDCOAuthSSLValidateServer Off
```
