### ISSUE TITLE
Create an initial group when using external auth

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-pods#508]
If a user configures OIDC, and also disables local login they won't be able to access the application unless they happen to have one of our pre-seeded groups configured in their auth server.

It would probably be better if we let the user provide us with an initial group name that we create at first boot. The user can then initially log in as a user in that group to configure the rest of the app.

Not sure of what needs to be done here for RBAC so that the initial group can create other groups and whatever else we want them to be able to do on that first login.

**Comment by carbonin** [comment]
@Fryguy do you think this should go in the CR directly or should we spec out some kind of application config that we can read in a separate tool?

I'm thinking if this gets any more complicated we might want a tool in the core repo to be able to read a yaml file or something and do all the configuration tasks we need it to. That way we will be able to cover it with better tests too.

**Comment by carbonin** [comment]
We could wrap the [auth config](https://github.com/ManageIQ/manageiq-pods/blob/3e0699ed3f4d530504f235c2593286fa2bacdb11/images/manageiq-orchestrator/container-assets/entrypoint#L19-L44) and maybe even the initial region creation and such into the same tool.

**Comment by Fryguy** [comment]
> I'm thinking if this gets any more complicated we might want a tool in the core repo to be able to read a yaml file or something and do all the configuration tasks we need it to.

Honestly, I thought this was a lot of what appliance_console_cli already does.  Not the group thing, specifically, but if you are configuring the app for appliances, we're going to want that same "first group" option as well, and appliance_console_cli is where that's ultimately going to end up.

**Comment by carbonin** [comment]
I think the problem is that the vast majority of what the appliance console cli does is write out httpd conf. The part we need so far is pretty small and it also seems odd to call out to the `appliance_console_cli` which then shells out to a rake task to configure settings. I guess I always considered the appliance console to be appliance-specific. Because 95% of it doesn't apply to containers it seemed strange to include.

**Comment by chessbyte** [comment]
So, it sounds like we should extract code from `appliance_console_cli` into a shared place that both the operator and the `appliance_console_cli` can use.

**Comment by carbonin** [comment]
@jvlcek would it be better to check the box to fetch the groups from the external system rather than creating a single group? That didn't work for us when we tested this out. What was the problem there?

**Comment by jvlcek** [comment]
> @jvlcek would it be better to check the box to fetch the groups from the external system rather than creating a single group? That didn't work for us when we tested this out. What was the problem there?

With OIDC the check box to fetch the groups from the external system should not be there. I just confirmed that in upstream it is not.

With other forms of external auth we use SSSD, which enables us to use dbus-send under the covers to query the Identity Provider for group membership. With OIDC/OAuth2 we don't use SSSD. So there is no easy way to query the IdP for a users group membership.

**Comment by carbonin** [comment]
> I just confirmed that in upstream it is not.

What does that mean? We were testing with Jansa, should we backport some change that removes it for OIDC?

**Comment by abellotti** [comment]
the "Get User Groups from External Authentication" should be there for all external auth, SSSD,SAML,OIDC.  What it essentially says is that with the groups we're getting for the external user, to go ahead and authorize him as such, i.e. define the user group membership in the user object.   As @jvlcek mentioned, we can fetch the group membership of a user via DBUS, i.e. when creating groups, there is a button to populate the groups pulldown, we can fetch on demand with MiqLdap and SSSD.   OIDC and SAML we cannot.

Anyways, this option does not create the groups themselves, just the group membership for the user. We still have to create the groups themselves (assigning the roles and such).  So this PR is needed for all (OIDC, SAML, SSSD, etc) and not just OIDC. Essentially eliminating the need for the manual process of creating the groups for the users in the UI if they chose not to use the OOTB EVM... ones.

**Comment by abellotti** [comment]
Which brings me to the next question :)  

Do we want them to only create the one (I presume super admin) or allow them to create multiple ?  With creating just the one, they can already use the API to create all the other ones if they want, but this will be one less step.

**Comment by abellotti** [comment]
For the groups, we just need the "description" and the "miq_user_role",  not sure how the latter will be specified here, but in the api, we allow role to be specified by name in addition to id or href.

```
{
   "description" : "new_group",
   "role" : { "name" : "EvmRole-super_administrator" }
}
```

For the operator, might be more elegant to have the group description and role_name pairs.

**Comment by carbonin** [comment]
I wanted to limit the complexity of what we're doing at deploy time because the operator never actually posts to the manageiq API. It is just a passthrough to some post-install step in the orchestrator entrypoint. This first pass would be similar to [how we configure the auth settings](https://github.com/ManageIQ/manageiq-pods/blob/f3372608b6654fcd2c699a7c7cf5174245f2fa94/images/manageiq-orchestrator/container-assets/entrypoint#L19-L44).

In the future I could see us having some operator-ish thing that we would run after we're sure the app is ready to do some post-install configuration of the application. I would expect something like that to take a more complex config-map or maybe a separate CR and could handle multiple groups, and possibly add providers. This would be an extension even of what I mentioned in https://github.com/ManageIQ/manageiq-pods/issues/508#issuecomment-630203984

For this pass I think limiting to a single group with an opinionated RBAC setup would probably be best.

**Comment by jvlcek** [comment]
Because  there are multiple similar things I will try to help clarify by distinguishing them.

1 - On the Configuration > Settings, Authentication page there is a checkbox labeled:
   `Get User Groups From External Authentication`

If this box is checked, when a user attempts to log in for the first time, if the groups returned by the Identity Provider match any already in the VMDB DB, the user record will be created and the user will be allowed to log in.

2 - On the Configuration > Access Control > Groups > Configuration (dropdown) > Add a new Group page is where the a button to populate the groups pulldown, which as Alberto mentioned can be used to fetch groups on demand with MiqLdap and SSSD but not with OIDC and SAML.

3 - We can use the API to create new groups

Here is the link to the ManageIQ API documentation: [API Create One Group Documentation](https://www.manageiq.org/docs/reference/latest/api/reference/groups#creating-groups)

Here is a ruby coding example: [API Create One Group Example](https://github.com/jvlcek/manageiq-api-examples/blob/master/primary_collections/groups/create_one_groups.rb)

The problem with using the API to create a group requires a user that can be Authenticated. So either a user must exist in the IdP that is a member of one of the groups pre-canned in ManageIQ or it is that admin user. Since we are going to disable the admin user using the API to create groups is not an option.

**Comment by jvlcek** [comment]
> I wanted to limit the complexity of what we're doing at 
>... (omitted text)
> For this pass I think limiting to a single group with an opinionated RBAC setup would probably be best.

I agree and once we have one user that can be Authenticated we can easily create more groups using the API.
