### ISSUE TITLE
Offline install for manageIQ

### ISSUE THREAD

**Issue by gyliu513** [ManageIQ/manageiq-pods#526]
In an offline OCP cluster, I can get all images from public and push into my local registry, but here the question for `orchestrator`, as it need to start up and create many worker pods, so how and where to push those worker image to enable the `orchestrator` can get those images from local registry? I did not found a configuration for this.

FYI @carbonin @Fryguy @chessbyte 

- ManageIQ version:
- Minikube/KIND/OCP/CRC version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

@miq-bot add-label bug

**Comment by carbonin** [comment]
The orchestrator uses the image namespace provided in [orchestratorImageNamespace](https://github.com/ManageIQ/manageiq-pods/blob/5185f6b5f2d068f66b51d7d9c8a69afcfa79c78a/manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml#L166-L169) for the worker images.

This is [passed as an env var](https://github.com/ManageIQ/manageiq-pods/blob/5185f6b5f2d068f66b51d7d9c8a69afcfa79c78a/manageiq-operator/pkg/helpers/miq-components/orchestrator.go#L120-L123) then [used to set the worker images](https://github.com/ManageIQ/manageiq/blob/af9ee0f6d79fc78037652e37e6b9a18ea59f7ffd/app/models/miq_worker/container_common.rb)

So to answer your question, you push the worker images to the same place as the orchestrator.
