### ISSUE TITLE
offline install failed

### ISSUE THREAD

**Issue by gyliu513** [ManageIQ/manageiq-pods#527]
Due to zookeeper and kafaka is using online docker image, and this will cause offline install failed.

- https://github.com/ManageIQ/manageiq-pods/blob/master/manageiq-operator/pkg/helpers/miq-components/kafka.go#L155
- https://github.com/ManageIQ/manageiq-pods/blob/master/manageiq-operator/pkg/helpers/miq-components/kafka.go#L252

FYI @carbonin @Fryguy

**Comment by Fryguy** [comment]
I'm not sure I understand.  You can override the Kafka deployment with your own deployment by giving it the location of the running Kafka.  In that case it shouldn't even try to pull the images

**Comment by carbonin** [comment]
>  In that case it shouldn't even try to pull the images

.... I'm not sure we got to this. I think it will still try to deploy the kafka and zookeeper pods.

**Comment by carbonin** [comment]
Same with PG IIRC.

**Comment by gyliu513** [comment]
@Fryguy @carbonin I think we cannot depend on external Kafka and Zookeeper, one proposal is also setting those images in the CR so that the end user can also customize the location of those images.

**Comment by carbonin** [comment]
:+1: That would be consistent with the other images as well so we can do that as a fix for this issue.

I'll probably open another issue to handle not deploying the database/kafka when a user provides a secret for either of those services.

**Comment by gyliu513** [comment]
> I'll probably open another issue to handle not deploying the database/kafka when a user provides a secret for either of those services.

Great, thanks @carbonin
