### ISSUE TITLE
Don't deploy the database/kafka if the user provides the corresponding secret

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-pods#529]
We shouldn't deploy our own database or kafka instance if the user has directed us to use an external one. At a minimum we should only deploy if we're creating the secret, but it might be good to go as far as reading the hostname from the secret to ensure that they're not just providing a user or password or something like that.

[ ] For PostgreSQL/Kafka - https://github.com/ManageIQ/manageiq-pods/pull/604

@miq-bot add-label enhancement

**Comment by Fryguy** [comment]
@gtanzillo This needs to be P1

**Comment by abellotti** [comment]
[ ] For PostgreSQL - https://github.com/ManageIQ/manageiq-pods/pull/604
