### ISSUE TITLE
The cockpit redirects and role don't work

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-pods#531]
When the "Cockpit" role is enabled, the orchestrator starts a worker on the local pod.
I guess the expected behavior would be to create a separate service worker that would handle the redirecting to the VM cockpit UI, but I don't know enough about how the worker works to say for sure.

1. Enable the "Cockpit" role.
2. Add a provider which manages a VM which is running cockpit.
3. Attempt to access the VMs cockpit UI from the "Access > Web Console" button on the VM summary screen

This should redirect me to the cockpit login page from the selected VM. But instead brings me to the following url which clearly will never work: `https://<orchestrator-pod-ip>/cws/=<vm-ip>`

For this to work, as a start we would need to get the application domain into that url and get `/cws` to direct us to the cockpit worker, which also needs to be in it's own deployment, and have a service. Then we would need to ensure that the actual cockpit worker will work correctly in a container which IIRC is not a guarantee as it utilizes Drb in some way (I don't remember how).

- ManageIQ version: master
- Minikube/KIND/OCP/CRC version: 3.11

**Comment by kbrock** [comment]
this redirect from one server to another behavior is handled by cockpit-bridge. But running a cockpit webservice (which was designed to run from systemd not from the command line as a worker) handles administration of the local process, as well. This doesn't seem like the intent I understood from what little I've read.

**Comment by chessbyte** [comment]
@kbrock @Fryguy I am assuming this can be closed with the recent removal of cockpit from ManageIQ?

**Comment by kbrock** [comment]
yes, we no longer have cockpit in our product
