### ISSUE TITLE
Support OIDC for SUI

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-pods#556]
Do https://github.com/ManageIQ/manageiq-appliance/pull/287 for the pods deployment

**Comment by carbonin** [comment]
@abellotti this is resolved in https://github.com/ManageIQ/manageiq-pods/pull/559, right?

**Comment by abellotti** [comment]
yes sir.

**Comment by carbonin** [comment]
Closed via https://github.com/ManageIQ/manageiq-pods/pull/559
