### ISSUE TITLE
Handle upgrades

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-pods#565]
We should have a plan for handling minor and major upgrades.

For a minor upgrade, this should mean just changing the image tag in the CR for the orchestrator and workers to the new released version.
  - This will require https://github.com/ManageIQ/manageiq-pods/issues/438 being solved for the orchestrator

For a major upgrade the amount of work will depend on if we have to update the operator. In my mind some reasonable solutions could be:
  1. Mapping the operator version to major ManageIQ releases like we do for the schema repo.
     - This would mean that the openshift resources wouldn't be allowed to change within a major version
     - An upgrade would mean re-deploying the operator image which would then run the reconcile loop to fix the resources deployed in the environment.
  2. Make the desired version a parameter in the CR.
     - This would mean that each new operator version needs to know what to deploy for all supported major releases and would also need to know how to change between them.
  3. Some kind of hybrid? Maybe we run an operator container/pod/deployment for each major version and pass on reconciling a CR if the version doesn't apply to the current runtime? Each major branch would build the operator for each release but the deployment would run all of the released operators.

I'm partial to option 1 as that seems the cleanest. I'm not sure if there are any best practices for this (maybe OLM would be involved), but it seems easiest to keep things contained to the operator rather than involving more external systems for the time being.

**Comment by bdunne** [comment]
Closing as this is on the Kasparov milestone and we have some logic in place to handle upgrades.  We can open more specific issues if we need something else done.
