### ISSUE TITLE
Remove the templates

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/manageiq-pods#584]
At this point I think the operator is more fully featured than the templates so it's probably time to stop trying to maintain both installation methods.

I think the only thing we would want to keep around would be the templates for the backup and restore jobs. Restore might need a bit of documentation and possibly an operator enhancement. Right now we assume the orchestrator is down when doing a restore and I think the operator will enforce a singe replica.

**Comment by bdunne** [comment]
Fixed by: https://github.com/ManageIQ/manageiq-pods/pull/656
