### ISSUE TITLE
manageiq-decorators aren't included

### ISSUE THREAD

**Issue by ahrechushkin** [ManageIQ/manageiq-pods#592]
```
[----] W, [2020-07-16T15:41:46.092407 #8:2ae1cdb7f960]  WARN -- : <AuditFailure> MIQ(Async.rescue in _async_generate_table) userid: [admin] - uninitialized constant ApplicationController::QuadiconHelper
[----] E, [2020-07-16T15:41:46.104278 #8:2ae1cdb7f960] ERROR -- : MIQ(MiqQueue#deliver) Message id: [26000001131506], Error: [uninitialized constant ApplicationController::QuadiconHelper]
[----] E, [2020-07-16T15:41:46.104770 #8:2ae1cdb7f960] ERROR -- : [NameError]: uninitialized constant ApplicationController::QuadiconHelper  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2020-07-16T15:41:46.105290 #8:2ae1cdb7f960] ERROR -- : /opt/manageiq/manageiq-ui-classic/app/controllers/application_controller.rb:41:in `<class:ApplicationController>'
```
I tried to collect cb report

- ManageIQ version Jansa
- OpenShift version

@miq-bot add-label bug

**Comment by skateman** [comment]
I guess the problem is that the decorators are being used in the affected pod, but not loaded.

**Comment by bdunne** [comment]
@ahrechushkin Which pod did this log come from?

**Comment by Fryguy** [comment]
@ahrechushkin Which ManageIQ version specifically?  I ask because we had started an rc build which had build issues.

**Comment by ahrechushkin** [comment]
@bdunne generic-worker pod
@Fryguy jansa

**Comment by Fryguy** [comment]
Ok that's strange, then... Will take a look.

cc @simaishi

**Comment by simaishi** [comment]
@ahrechushkin were the images pulled from ManageIQ docker hub registry?

**Comment by ahrechushkin** [comment]
@simaishi no, image builds with manageiq-pods

**Comment by simaishi** [comment]
@ahrechushkin is this still an issue? If it is, please share the details of your build. Based on the error message where it shows the path to the ui-classic repo is `/opt/manageiq/manageiq-ui-classic`, you're doing something different in your build and the files are not in the normal location.

**Comment by ahrechushkin** [comment]
Hello! @simaishi 
Actually i fixed this problem
idn how it work in your builds, cause we aren't use miq rpms
