### ISSUE TITLE
ManageIQ Operator P1 Issues for Kasparov

### ISSUE THREAD

**Issue by gtanzillo** [ManageIQ/manageiq-pods#598]
The following issues are designated as priority 1 for the Kasparov release

- [x] [Backup and Restore in the Operator](https://github.com/ManageIQ/manageiq-pods/issues/489) (Brandon)
- [x] [Don't deploy the database/kafka if the user provides the corresponding secret](https://github.com/ManageIQ/manageiq-pods/issues/529) (Alberto)

**Comment by Fryguy** [comment]
I've remove the documentation effort, because that has nothing to do with the operator.  Instead I've made https://github.com/ManageIQ/manageiq-documentation/issues/1449 its own card on the roadmap.
