### ISSUE TITLE
Add a release task to update image tags for tagged (=release) build

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq-pods#602]
As discussed in https://github.com/ManageIQ/manageiq-pods/pull/600

@miq-bot add-label enhancement

**Comment by chessbyte** [comment]
@Fryguy please opine on the best approach

**Comment by Fryguy** [comment]
We could do a rake task like in other repos, but we're trying to avoid ruby code here eventually... Maybe a Makefile?  I'm not sure.
