### ISSUE TITLE
Incorrect permissions on files in APP_ROOT

### ISSUE THREAD

**Issue by jvlcek** [ManageIQ/manageiq-pods#610]
Issue Description:

Some pods crash on deployment

```bash
$ oc get pods | grep Crash
1-remote-console-87ff969d5-vnrd5   0/1     CrashLoopBackOff   30         2h
1-web-service-8567b96f65-tm4q2     0/1     CrashLoopBackOff   30         2h
```

The logs in the failing pods all indicate a permissions error.

e.g.:

```bash
$ oc logs 1-remote-console-87ff969d5-vnrd5
== Writing encryption key ==
/usr/local/bin/entrypoint: line 6: /var/www/miq/vmdb/certs/v2_key: Permission denied
/usr/local/bin/entrypoint: line 12: /var/www/miq/vmdb/GUID: Permission denied
/usr/share/ruby/logger.rb:752:in `initialize': Permission denied @ rb_sysopen - /var/www/miq/vmdb/log/evm.log (Errno::EACCES)
	from /usr/share/ruby/logger.rb:752:in `open'
	from /usr/share/ruby/logger.rb:752:in `create_logfile'
...
```

The pods that **are not** crashing have file mode 775 on APP_ROOT

```bash
$ oc rsh 1-generic-cb5d9b7d8-gnk2s 
sh-4.4$ ls -aFld $APP_ROOT         
drwxrwxr-x. 18 root root 4096 Aug 11 15:05 /var/www/miq/vmdb/
```

The pods that **are** crashing have file mode 755 on APP_ROOT

```bash
<Debug in Terminal via Openshift UI>
sh-4.4$ ls -aFld $APP_ROOT
drwxr-xr-x. 18 root root 4096 Aug 10 01:38 /var/www/miq/vmdb/
```

It appears that the dnf install command in images/manageiq-webserver-worker/Dockerfile could be augmented to set the mode with:

```diff
-RUN dnf -y --disableplugin=subscription-manager --setopt=tsflags=nodocs install ${RPM_PREFIX}-ui && dnf clean all
+RUN dnf -y --disableplugin=subscription-manager --setopt=tsflags=nodocs install ${RPM_PREFIX}-ui && \
+    dnf clean all && \
+    chgrp -R 0 $APP_ROOT && \
+    chmod -R g=u $APP_ROOT
```

A better fix may be to leverage the %defattr directive in the spec file here:

https://github.com/ManageIQ/manageiq-rpm_build/blob/master/rpm_spec/subpackages/manageiq-ui#L10

Still investigating why this issue is sporadic.

**Comment by chessbyte** [comment]
cc @simaishi

**Comment by simaishi** [comment]
@jvlcek Do you have an example of working and non-working build?  I can take a look at the images and build logs to see if there is anything that's different, if you know exactly which image works and not.

**Comment by jvlcek** [comment]
@simaishi I was just launching from latest. @bdunne, @abellotti and I all encountered this issue with the latest images. @bdunne Posted a PR with the fix.

**Comment by simaishi** [comment]
Yes, I know there is a PR, but I'm just trying to understand why the behavior is inconsistent. Do you know which image worked?

**Comment by jvlcek** [comment]
When I tried to launch yesterday I hit this issue. Last week I did not. I've used the default latest images both times.

**Comment by chessbyte** [comment]
Fixed via https://github.com/ManageIQ/manageiq-rpm_build/pull/82
