### ISSUE TITLE
Steps for Kubernetes deployment

### ISSUE THREAD

**Issue by srajmane** [ManageIQ/manageiq-pods#612]
How to deploy ManagIQ in Kubernetes on Intel Ubuntu 18.04?  Please provide steps.

Thanks in advance.
@miq-bot add-label question
@miq-bot add-label help wanted

**Comment by chessbyte** [comment]
@carbonin I thought you wrote documentation for this but cannot find it.  cc @Fryguy @gtanzillo @bdunne @abellotti @jvlcek

**Comment by carbonin** [comment]
https://www.manageiq.org/docs/get-started/kubernetes and also https://github.com/ManageIQ/manageiq-pods#kubernetes-support

**Comment by carbonin** [comment]
Also https://github.com/ManageIQ/manageiq-pods/issues/351 is still open to make it more clear in the README

**Comment by chessbyte** [comment]
@srajmane Please read the documents linked [above](https://github.com/ManageIQ/manageiq-pods/issues/612#issuecomment-673458605).  If you find anything that does not work or where the instructions are wrong, please let us know by opening an issue.

**Comment by srajmane** [comment]
> @srajmane Please read the documents linked [above](https://github.com/ManageIQ/manageiq-pods/issues/612#issuecomment-673458605). If you find anything that does not work or where the instructions are wrong, please let us know by opening an issue.

@chessbyte and @carbonin I didn't install oc, is it possible to deploy ManageIQ in Kubernetes without openshift?

**Comment by chessbyte** [comment]
> I didn't install oc, is it possible to deploy ManageIQ in Kubernetes without openshift?

can `kubectl` be used instead of `oc`?

**Comment by carbonin** [comment]
Not with the templates. I would suggest using the operator in that case.

**Comment by chessbyte** [comment]
@carbonin at this point, is there any reason to NOT use the ManageIQ operator for podified deployments?

**Comment by carbonin** [comment]
Nope, that's why I opened https://github.com/ManageIQ/manageiq-pods/issues/584 :wink:

**Comment by carbonin** [comment]
And by extension https://github.com/ManageIQ/manageiq.org/issues/867

**Comment by srajmane** [comment]
@carbonin Any documentation to deploy ManageIQ with operator?

**Comment by bdunne** [comment]
@srajmane Here is the documentation for the operator: https://github.com/ManageIQ/manageiq-pods/blob/master/manageiq-operator/README.md
