### ISSUE TITLE
How does one deploy CloudForms distributed deployment with podified CF?

### ISSUE THREAD

**Issue by vsarana** [ManageIQ/manageiq-pods#633]
We have deployed the new podified version of Cloudforms as part of CP4MCM 2.x ,  but we don't see the way to change the cloudforms deployment topology to master-region architecture with podified version being the master and appliance versions are the regions,

For Reference, we are trying to deploy the architecture as described in the deployment planning guide.   

https://www.ibm.com/support/knowledgecenter/en/SSFC4F_2.0.0/Infra_mgmt/deployment_planning_guide/index.html#regions

We don;t see a way to perform the operations to designate the podified version as master such as run appliance_console commands to configure database, export SSL certs, etc.   

For example:  We don't see a way to perform the step below.

https://www.ibm.com/support/knowledgecenter/en/SSFC4F_2.0.0/Infra_mgmt/installing_on_vmware_vsphere/index.html#configuring-an-external-database

Can someone clarify, how the multi-region deployment can be performed with a mixture of podified and appliance based CF in CP4MCM 2.0?

**Comment by bdunne** [comment]
To set the region, specify the `databaseRegion` in the CR during deployment.  If not specified, it defaults to 0. https://github.com/ManageIQ/manageiq-pods/blob/master/manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml#L45

**Comment by bdunne** [comment]
If a remote region were in a podified environment, it would require that the database service be exposed on a node port.  The global region shouldn't require anything extra.

**Comment by bdunne** [comment]
If you want to use an external database rather than deploying it in the application namespace, create a database secret containing the connection information and that will be used instead. https://github.com/ManageIQ/manageiq-pods/tree/master/manageiq-operator#configuring-external-postgres

**Comment by gtanzillo** [comment]
Closing since the original question was answered
