### ISSUE TITLE
Create an image build Dockerfile that includes the VDDK

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-pods#635]
While we can't actually build with the VDDK, we _can_ create a Dockerfile given someone has the VDDK and we can fetch it.  Not sure if an ARG with a URL is the best way or a COPY command, but having a Dockerfile would make the steps to rebuild the image including the VDDK much simpler.

@miq-bot add-label enhancement

**Comment by bdunne** [comment]
Closing as duplicate of https://github.com/ManageIQ/manageiq-pods/issues/538
