### ISSUE TITLE
container_env is relatively slow

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/manageiq-pods#695]
Using the following script to profile bash, we can see 3 commands make container_env slow:

```
PS4='+ $(date "+%s.%N")\011 '
set -x

source /var/www/miq/vmdb/container_env

set +x
```
https://gist.github.com/jrafanie/56273d25ac84fefa54f8c2299c79ac7e

EDIT: this brilliant hack came from this: https://stackoverflow.com/a/5015179

1) gem env path 0.32888 from the gemset enable
2) 2 calls to CGI escape the DB user and password, roughly 0.14 seconds each

![Screen Shot 2021-03-10 at 4 20 56 PM](https://user-images.githubusercontent.com/19339/110703225-80880080-81c1-11eb-9f00-a34a43e052db.png)

Note, this is much less of a problem now that the liveness probe [no longer calls container_env every 15 seconds](https://github.com/ManageIQ/manageiq/issues/21090), but this was opened so we can investigate solutions if it's needed to be run more often than 1) once during the pod entrypoint and 2) whenever I need to rsh in and load the ruby environment.

@miq-bot add-label bug

**Comment by Fryguy** [comment]
The `gem env path` comes from here: https://github.com/ManageIQ/manageiq-rpm_build/blob/8f66a73a18dffbc73af613e4ce5dd611e7d75c1e/rpm_spec/manageiq.spec.in#L54 .  The purpose of this enable script is when the gemset rpm is enabled, we need to prepend our gemset gem path to the existing gem path.  However, at this point, GEM_PATH is not yet defined, so we need to figure out what the current one is.  There might be a more efficient method to this than shelling out.  Since this is for containers we _might_ be able to just hardcode the path, but if things change, we're going to have to remember to change this as well.

**Comment by Fryguy** [comment]
For the CGI.escape, https://github.com/ManageIQ/manageiq-pods/pull/694 will cut the time a bit.  If we really care to make it faster we can also just smash the 2 separate calls into a single call which should give us another 2x (since the expensive part is starting ruby itself).  Alternatively, there might be a shell function we can grab to avoid ruby altogether.

**Comment by Fryguy** [comment]
@jrafanie For the gem env path, I'm seeing roughly 50% improvement locally if I do this:

```
$ time gem env path
/Users/jfrey/.gem/ruby/2.6.6:/Users/jfrey/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0
0.09s user 0.03s system 96% cpu 0.131 total

$ time ruby -e "puts Gem.path.join(File::PATH_SEPARATOR)"
/Users/jfrey/.gem/ruby/2.6.6:/Users/jfrey/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0
0.05s user 0.02s system 93% cpu 0.075 total
```

cc @NickLaMuro

**Comment by Fryguy** [comment]
cc @kbrock - This is what I was talking about with respect to gem env... hardcoding the paths will eliminate the minor performance blip here.

**Comment by kbrock** [comment]
yea. I was concerned about this at first but it makes a lot of sense for locking things down and happens to have a performance boost also.

**Comment by kbrock** [comment]
yea - I changed that one line and it makes a big difference.
Since I would like our path to be more locked down, this works for me.

The change I was proposing is: https://github.com/ManageIQ/manageiq-appliance/pull/309/files

```
[root@localhost ~]# time sh /opt/manageiq/manageiq-gemset/enable

real	0m2.768s
user	0m2.157s
sys	0m0.339s
[root@localhost ~]# time sh /opt/manageiq/manageiq-gemset/enable

real	0m2.718s
user	0m2.128s
sys	0m0.248s
[root@localhost ~]# time sh /opt/manageiq/manageiq-gemset/enable2

real	0m0.003s
user	0m0.003s
sys	0m0.001s
[root@localhost ~]# time sh /opt/manageiq/manageiq-gemset/enable2

real	0m0.004s
user	0m0.003s
sys	0m0.001s
```

**Comment by jrafanie** [comment]
I'm good with implementing improvements.  It looks like there are logical non-performance reasons to do that PR.  Maybe we'll watch that PR and close this if those logical changes have the side effect of improving the performance as described above.

**Comment by kbrock** [comment]
Is there a way to find out if this has been resolved?

**Comment by jrafanie** [comment]
yeah, I provided the script in the description... run it in a new pod and see if any step is > 0.1 second... set+x shows it in seconds, so look for gaps of > 0.1 second.

**Comment by Fryguy** [comment]
This might be down to nothing now - @kbrock Can you verify with @jrafanie's script and if so, we can close this one as completed.

**Comment by bdunne** [comment]
I think we're done here.  Total time `0.540126774` on `docker.io/manageiq/manageiq-base-worker:latest` SHA `4b412d4fa2b6b6a32b8028890a1bacecbb45a62ecfc0f7d1ff41bb3cbf6b7f01`
```
++ 1630359175.798570527	 source /var/www/miq/vmdb/container_env
+++ 1630359175.821561561	 update-ca-trust
+++ 1630359176.119577851	 [[ -s /etc/default/evm ]]
+++ 1630359176.122518401	 source /etc/default/evm
++++ 1630359176.125497574	 for prop in /etc/default/*.properties
++++ 1630359176.128275351	 [[ -e /etc/default/manageiq-productization.properties ]]
+++++ 1630359176.132255057	 xargs
+++++ 1630359176.132261293	 sed -e 's/^[#;].*//g' /etc/default/manageiq-productization.properties
++++ 1630359176.143809026	 export APPLIANCE_SOURCE_DIRECTORY=/opt/manageiq/manageiq-appliance APPLIANCE_TEMPLATE_DIRECTORY=/opt/manageiq/manageiq-appliance/TEMPLATE GEM_HOME=/opt/manageiq/manageiq-gemset GEM_PATH=/opt/manageiq/manageiq-gemset:/usr/share/gems:/usr/local/share/gems PATH=/opt/manageiq/manageiq-gemset/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
++++ 1630359176.147050857	 APPLIANCE_SOURCE_DIRECTORY=/opt/manageiq/manageiq-appliance
++++ 1630359176.150528598	 APPLIANCE_TEMPLATE_DIRECTORY=/opt/manageiq/manageiq-appliance/TEMPLATE
++++ 1630359176.153761070	 GEM_HOME=/opt/manageiq/manageiq-gemset
++++ 1630359176.157114824	 GEM_PATH=/opt/manageiq/manageiq-gemset:/usr/share/gems:/usr/local/share/gems
++++ 1630359176.160418537	 PATH=/opt/manageiq/manageiq-gemset/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
++++ 1630359176.163377862	 for prop in /etc/default/*.properties
++++ 1630359176.166331171	 [[ -e /etc/default/manageiq.properties ]]
+++++ 1630359176.170290654	 xargs
+++++ 1630359176.171071419	 sed -e 's/^[#;].*//g' /etc/default/manageiq.properties
++++ 1630359176.179654215	 export RAILS_ENV=production APPLIANCE=true EXECJS_RUNTIME=Node MALLOC_ARENA_MAX=1 KEY_ROOT=/var/www/miq/vmdb/certs BUNDLE_GEMFILE=/var/www/miq/vmdb/Gemfile LANGUAGE=en_US.UTF-8 LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 APPLIANCE_PG_CTL=/usr/bin/pg_ctl APPLIANCE_PG_MOUNT_POINT=/var/lib/pgsql APPLIANCE_PG_DATA=/var/lib/pgsql/data APPLIANCE_PG_SERVICE=postgresql APPLIANCE_PG_PACKAGE_NAME=postgresql-server RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000 RUBY_GC_HEAP_INIT_SLOTS=600000 RUBY_GC_HEAP_GROWTH_FACTOR=1.25 ANSIBLE_LOCAL_TEMP=/tmp/.ansible_local_tmp ANSIBLE_REMOTE_TEMP=/tmp/.ansible_remote_tmp
++++ 1630359176.183284252	 RAILS_ENV=production
++++ 1630359176.186873353	 APPLIANCE=true
++++ 1630359176.190370416	 EXECJS_RUNTIME=Node
++++ 1630359176.193361914	 MALLOC_ARENA_MAX=1
++++ 1630359176.196414719	 KEY_ROOT=/var/www/miq/vmdb/certs
++++ 1630359176.199805587	 BUNDLE_GEMFILE=/var/www/miq/vmdb/Gemfile
++++ 1630359176.202983282	 LANGUAGE=en_US.UTF-8
++++ 1630359176.206042532	 LANG=en_US.UTF-8
++++ 1630359176.209140568	 LC_CTYPE=en_US.UTF-8
++++ 1630359176.212783226	 APPLIANCE_PG_CTL=/usr/bin/pg_ctl
++++ 1630359176.216315387	 APPLIANCE_PG_MOUNT_POINT=/var/lib/pgsql
++++ 1630359176.220341430	 APPLIANCE_PG_DATA=/var/lib/pgsql/data
++++ 1630359176.223556894	 APPLIANCE_PG_SERVICE=postgresql
++++ 1630359176.227237300	 APPLIANCE_PG_PACKAGE_NAME=postgresql-server
++++ 1630359176.230188366	 RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
++++ 1630359176.233174685	 RUBY_GC_HEAP_INIT_SLOTS=600000
++++ 1630359176.236028659	 RUBY_GC_HEAP_GROWTH_FACTOR=1.25
++++ 1630359176.239058267	 ANSIBLE_LOCAL_TEMP=/tmp/.ansible_local_tmp
++++ 1630359176.241996983	 ANSIBLE_REMOTE_TEMP=/tmp/.ansible_remote_tmp
++++ 1630359176.245471627	 urlescape
++++ 1630359176.249231316	 PAYLOAD=
++++ 1630359176.252445083	 ruby --disable-gems -rcgi -e 'puts CGI.escape(ENV['\''PAYLOAD'\''])'
+++ 1630359176.283458503	 safeuser=
++++ 1630359176.286952635	 urlescape
++++ 1630359176.290358481	 PAYLOAD=
++++ 1630359176.293817796	 ruby --disable-gems -rcgi -e 'puts CGI.escape(ENV['\''PAYLOAD'\''])'
+++ 1630359176.321826455	 safepass=
+++ 1630359176.325017256	 database_url='postgresql://:@:/?encoding=utf8&pool=5&wait_timeout=5&sslmode=prefer'
+++ 1630359176.328268220	 [[ -f /.postgresql/root.crt ]]
+++ 1630359176.331467584	 export 'DATABASE_URL=postgresql://:@:/?encoding=utf8&pool=5&wait_timeout=5&sslmode=prefer'
+++ 1630359176.334799311	 DATABASE_URL='postgresql://:@:/?encoding=utf8&pool=5&wait_timeout=5&sslmode=prefer'
++ 1630359176.338697301	 set +x
```

`update-ca-trust` takes the longest at `0.29801629s`, but I don't think there's much we are going to do about that.

**Comment by Fryguy** [comment]
@bdunne We only need to update-ca-trust if there's a cert in place right?  Can we check before calling it?

**Comment by jrafanie** [comment]
It's worth pointing out that the `gem env path` was hardcoded in https://github.com/ManageIQ/manageiq-rpm_build/pull/145 to make it faster thanks to @kbrock and @Fryguy's comment here:  https://github.com/ManageIQ/manageiq-pods/issues/695#issuecomment-796795082

**Comment by kbrock** [comment]
In an appliance, `update-ca-trust` is at least 20x slower than `evm` (loading the properties files)
Also, there are all these `if` checks. I assumed that these values are pretty constant.

Can we use [[bash]](https://gist.github.com/cdown/1163649) to decode these cgi instead of using ruby? 
I am testing an alternative to `/etc/default/evm` that doesn't shell out so it takes closer to 0.002s real. I'll put together a PR

```
[root@localhost ~]# time source /etc/default/evm

real	0m0.012s
user	0m0.006s
sys	0m0.008s
[root@localhost ~]# time update-ca-trust

real	0m0.243s
user	0m0.180s
sys	0m0.033s
```

**Comment by bdunne** [comment]
> @bdunne We only need to update-ca-trust if there's a cert in place right? Can we check before calling it?

Yeah, this can check for the presence of certificate files and subdirectories of `/etc/pki/ca-trust/source/` as a conditional.

**Comment by jrafanie** [comment]
Note, I'm not seeing [the removal of gem env path](https://github.com/ManageIQ/manageiq-rpm_build/pull/145/commits/242e1d423966c1ccf8f06a37b269f8d8b2a2da80) in any released manageiq-base-worker podified image, which is expected since it wasn't backported but even latest doesn't have it: 

```
% docker image list | grep "manageiq/manageiq-base"
manageiq/manageiq-base-worker                                                                          latest-morphy   c8ecc5bc89de   15 hours ago    2.01GB
manageiq/manageiq-base-worker                                                                          latest          c4d29cf656ef   25 hours ago    2.01GB
manageiq/manageiq-base-worker                                                                          jansa-4         4ffc2a5a71dd   2 months ago    2.3GB
manageiq/manageiq-base-worker                                                                          lasker-1        8433d2c48158   2 months ago    1.92GB
manageiq/manageiq-base-worker                                                                          kasparov-1      dbba0ce9e18b   8 months ago    2.17GB
manageiq/manageiq-base-worker                                                                          jansa-3         8443b4875e09   8 months ago    2.13GB
manageiq/manageiq-base-worker                                                                          jansa-2         bc9c96853a9c   11 months ago   2.09GB
```

I can see that even morphy branch has [gem env path](https://github.com/ManageIQ/manageiq-rpm_build/blob/morphy/rpm_spec/manageiq.spec.in#L54) but I was surprised that latest builds weren't pulling in master of rpm_build.

```
% docker run --rm -it docker.io/manageiq/manageiq-base-worker:latest /bin/bash
[root@89e898f3cc0e /]# cat /opt/manageiq/manageiq-gemset/enable
export APPLIANCE="true"
export BUNDLE_GEMFILE=/var/www/miq/vmdb/Gemfile
export GEM_HOME=/opt/manageiq/manageiq-gemset
export GEM_PATH=/opt/manageiq/manageiq-gemset:$(gem env path)
export PATH=/opt/manageiq/manageiq-gemset/bin:$PATH
```

I was going to close this but noticed that latest was still bad.  Maybe there's a good reason we're not using the master branch of rpm_build on latest but it still looked bad, especially when `update-ca-trust` was added in latest and isn't offset by the removal of `gem env path`.

```
% docker run --rm -it docker.io/manageiq/manageiq-base-worker:latest /bin/bash
[root@11ed9604dd92 /]# time source /var/www/miq/vmdb/container_env
real  0m0.504s

% docker run --rm -it docker.io/manageiq/manageiq-base-worker:latest-morphy /bin/bash
[root@cb76d085b6b0 /]# time source /var/www/miq/vmdb/container_env
real  0m0.281s

% docker run --rm -it docker.io/manageiq/manageiq-base-worker:lasker-1 /bin/bash
[root@b0e911f6ad44 /]# time source /var/www/miq/vmdb/container_env
real  0m0.282s

% docker run --rm -it docker.io/manageiq/manageiq-base-worker:jansa-2 /bin/bash
[root@ff6d1e25e61c /]# time source /var/www/miq/vmdb/container_env
real  0m0.383s

% docker run --rm -it docker.io/manageiq/manageiq-base-worker:jansa-3 /bin/bash
[root@223b9cb46763 /]# time source /var/www/miq/vmdb/container_env
real  0m0.382s

% docker run --rm -it docker.io/manageiq/manageiq-base-worker:jansa-4 /bin/bash
[root@e04633508271 /]# time source /var/www/miq/vmdb/container_env
real  0m0.377s
```

**Comment by jrafanie** [comment]
![image](https://user-images.githubusercontent.com/19339/135655231-2f201fdc-8ba5-4510-9397-0467d351d6a4.png)

From latest...
[container_env_timings_latest.csv](https://github.com/ManageIQ/manageiq-pods/files/7268719/container_env_timings_latest.csv)

**Comment by Fryguy** [comment]
@jrafanie Did something not get backported? If so, please mark is as `morphy/yes?`

**Comment by Fryguy** [comment]
Looks like we need https://github.com/ManageIQ/manageiq-rpm_build/pull/145 and maybe some of the followup PRs.  @kbrock - you good with these coming back?

**Comment by jrafanie** [comment]
> @jrafanie Did something not get backported? If so, please mark is as `morphy/yes?`

I don't know, I accidentally added morphy.  I was talking about master.  It looks like we're not using master branch of rpm_build repo for `latest` container images.  

Re: morphy.  Do we want it on morphy?  It was an enhancement and I'm not really pushing for it on morphy, just surprised it's not on master.  I don't know how rpm_build gets pulled into latest images.

**Comment by Fryguy** [comment]
I'm +1 for it on morphy because it was also a part of the slow liveness probes.

> It looks like we're not using master branch of rpm_build repo for latest container images.

@bdunne can you comment on this?

**Comment by jrafanie** [comment]
https://github.com/ManageIQ/manageiq-rpm_build/blob/master/rpm_spec/manageiq.spec.in#L54 is master and doesn't contain the `gem env path`

**Comment by Fryguy** [comment]
master showing the wrong thing should be fixed by https://github.com/ManageIQ/manageiq-pods/pull/758

**Comment by jrafanie** [comment]
I created https://github.com/ManageIQ/manageiq-pods/issues/759 for the master/latest issue which is resolved by #758

**Comment by jrafanie** [comment]
@kbrock What do you think of a manual backport of just the `gem env path` hardcode commit to morphy?  https://github.com/ManageIQ/manageiq-rpm_build/pull/145/commits/242e1d423966c1ccf8f06a37b269f8d8b2a2da80

I don't know that we want all of the properties and dependent changes backported but `gem env path` seems like a harmless change to speed up `container_env`.  cc @bdunne @Fryguy

**Comment by kbrock** [comment]
That whole commit can go across and would be compatible with any version of our app.

the other change will not make any difference and I'd prefer if we can keep a whole commit together:
This change just hardcodes the full path into 2 places instead of using a var to set one from the other

```diff
  export APPLIANCE_SOURCE_DIRECTORY=%{appliance_root}
- export APPLIANCE_TEMPLATE_DIRECTORY=${APPLIANCE_SOURCE_DIRECTORY}/TEMPLATE
+ export APPLIANCE_TEMPLATE_DIRECTORY=%{appliance_root}/TEMPLATE
```

**Comment by kbrock** [comment]
I do not think we want to port the environment changes. That has deep ties into our systemd fixes. it involves moving the systemd.service files from one repo to another and other work that is probably far too invasive.

Just porting the hardcoded path was by far our biggest improvement there.

**Comment by jrafanie** [comment]
> Just porting the hardcoded path was by far our biggest improvement there.

@kbrock can you open a direct PR to morphy for just that fix?  We can discuss if we want to merge it there.  Personally, I feel it's so little risk, I'd be fine with it.

**Comment by kbrock** [comment]
Sounds like a plan: https://github.com/ManageIQ/manageiq-rpm_build/pull/210

**Comment by kbrock** [comment]
have we found a better time to update our ca?
It seems like we may be able to conditionally call `update-ca-trust` or maybe call it when we update the cert rather than here?

**Comment by bdunne** [comment]
🤷🏻‍♂️ We don't update the cert, it's provided through a secret mount when the pod is launched.  I don't know when else to do it.

**Comment by kbrock** [comment]
Is there a hook in our boot process instead of each time we run a login shell?

**Comment by Fryguy** [comment]
container_env is the hook at the moment, though, I like the idea of maybe splitting that?

**Comment by Fryguy** [comment]
Actually, if we split it, it won't make a difference...when a user runs a container manually (for example to get a bash shell), they still need container_env, and will still need the certs if they want to do anything like connect to the database in a rails console.  I don't see any way around it.

The only thing I'm looking for is a simple 

```bash
[ -f "/etc/pki/..."] && update-ca-trust
```
