### ISSUE TITLE
Update CRDs from apiextensions.k8s.io/v1beta to apiextensions.k8s.io/v1to support Kubernetes 1.22+

### ISSUE THREAD

**Issue by evertmulder** [ManageIQ/manageiq-pods#777]
`apiextensions.k8s.io/v1beta1` CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; 
For 1.22+ `apiextensions.k8s.io/v1` CustomResourceDefinition should be used

See also https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122

https://github.com/ManageIQ/manageiq-pods/blob/master/manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml is using `apiextensions.k8s.io/v1beta1`

@miq-bot add-label enhancement

**Comment by Fryguy** [comment]
Good timing!  We happened to be working on that anyway. 😊
