### ISSUE TITLE
Check memcached pod status before we begin initialization

### ISSUE THREAD

**Issue by fbladilo** [ManageIQ/manageiq-pods#78]
@bazulay @simaishi @carbonin We need to check the status of the memcached POD before we begin initialization, similar to what we do with postgresql [here](https://github.com/ManageIQ/manageiq-pods/blob/master/images/miq-app/docker-assets/container-scripts/container-deploy-common.sh#L75).

In current deployments, the memcached POD comes online first, mainly because is a light-weight image/POD and we always allow an application initialization delay of 30 seconds [here](https://github.com/ManageIQ/manageiq-pods/blob/master/images/miq-app/docker-assets/appliance-initialize.sh#L9)

Ideally we would have a check_memcached_status function that ensures the availability of the service/pod before we begin. A simple TCP check on port 11211 should suffice or potentially we could use "memcached-tool" , example : 

```bash
[root@manageiq-0 vmdb]# memcached-tool memcached
  #  Item_Size  Max_age   Pages   Count   Full?  Evicted Evict_Time OOM
[root@manageiq-0 vmdb]# echo $?
0
[root@manageiq-0 vmdb]# memcached-tool memcached:11399
Couldn't connect to memcached:11399
[root@manageiq-0 vmdb]# echo $?
113
[root@manageiq-0 vmdb]# 
```
In any case, we will have to install either the memcached RPM on miq-app or whatever tool we use for checking the status of the service. Ideas/Opinions?

**Comment by bazulay** [comment]
@fbladilo  @simaishi  @carbonin  we could install the memcached rpm in the manageiq image , or we could check if the port is open using bash only (see http://stackoverflow.com/questions/4922943/test-from-shell-script-if-remote-tcp-port-is-open).

BTW what is the size of the rpm ?

**Comment by fbladilo** [comment]
@bazulay Size is minimal (84k), the advantage is that we will check status with the native tool : 

memcached                                 x86_64                                 1.4.15-9.el7_2.1                                    production-rhel-x86_64-workstation-7.2                                  84 k

**Comment by fbladilo** [comment]
@bazulay Yeah, I thought about this one, currently memcached is part of the base RHEL/Centos, that is actually how we build the image currently used on podified. We select the base images for the pods and must align to the desired base OS release for MIQ. 

Currently our base all across is Centos7/RHEL7. I think the misalignment case for base images seems remote but possible, that is, we are forced to bring up a Pod on a different base release AND assume that the interface changed enough for commands to not work properly..
 
Some options : 

Memcached native (memcached-tool) : 

Pros : Native, small size, could potentially be used for more extended checks not just port open.
Cons: Could potentially cause a base image misalignment as we are likely to be pulling these images in the future from a different source (SCL?)
 
Bash : 

Pros : Already installed on all appliances, independent from package versioning/interface.
Cons :  Newer bash packages could also introduce issues with the syntax/mechanism used, 
basic TCP check only. 

BTW, I have not tested the bash checks, they seem to rely on /dev/tcp which I'm not sure is a good idea on containers.

@carbonin @simaishi Ideas/Opinions :smile:

**Comment by carbonin** [comment]
I have no preference.

I feel like `ncat -z <host> 11211` is definitely simpler, especially if we want to avoid installing more rpms on the pods.

**Comment by fbladilo** [comment]
@carbonin Is nmap-ncat installed on MIQ VM appliances by default? On containers : 

[root@manageiq-2-myr0t vmdb]# rpm -qa | grep nmap
[root@manageiq-2-myr0t vmdb]# 

Hmm

**Comment by carbonin** [comment]
Oh maybe not .. didn't think of that :sweat_smile:

**Comment by fbladilo** [comment]
@carbonin I still like the idea :smiley: , since we can re-use it for other services, I'm not too fond of echoing to /dev/tcp on a container for service availability checks....

**Comment by carbonin** [comment]
Okay, plus it seems to make more sense to have ncat on the non-memcached containers rather than having memcached on the non-memcached containers.

> I'm not too fond of echoing to /dev/tcp on a container for service availability checks....

I'm not sure what solution this applies to ...

**Comment by carbonin** [comment]
Ah also it looks like it is installed on the VM image https://github.com/ManageIQ/manageiq-appliance-build/pull/115

**Comment by fbladilo** [comment]
@carbonin We use the miq POD (appliance) to perform all pre-initialization checks for service availability, bash built-in tcpchecks could be an option but I'm not too convinced on that option. Instead ncat seems like a better fit for the task and it is not too heavy in size. I wrote a function last night that uses ncat to perform validation, so far so good : 
```bash
[root@franco-master-ocp34 franco]# ./check_svc.sh google.com 80
== Checking google.com:80 status ==
google.com:80 - accepting connections
[root@franco-master-ocp34 franco]# ./check_svc.sh badhostn1.com 80
== Checking badhostn1.com:80 status ==
Ncat: Could not resolve hostname "badhostn1.com": Name or service not known. QUITTING.
Ncat: Could not resolve hostname "badhostn1.com": Name or service not known. QUITTING.
Ncat: Could not resolve hostname "badhostn1.com": Name or service not known. QUITTING.
^C
[root@franco-master-ocp34 franco]# ./check_svc.sh badhostn1.com
Error something seems wrong, we need at least two parameters to check service status
[root@franco-master-ocp34 franco]# ./check_svc.sh google.com 81
== Checking google.com:81 status ==
Ncat: Connection timed out.
Ncat: Connection timed out.
^C
```

It should be re-usable for any other future service checks we want to perform, it requires a service name (openshift DNS name) and service port.

**Comment by bazulay** [comment]
I am good installing ncat in the image and use it to check memcache pod.
I assume we'll be using it to validate more PODs down the road.
