### ISSUE TITLE
[RFE] Allow SSL/TLS communication between optional pods

### ISSUE THREAD

**Issue by bdunne** [ManageIQ/manageiq-pods#789]
Followup for optional services from: https://github.com/ManageIQ/manageiq-pods/issues/724

- [ ] Secure communication to kafka/zookeeper services

**Comment by nasark** [comment]
PR https://github.com/ManageIQ/manageiq-pods/pull/951

**Comment by bdunne** [comment]
Closing since we now use strimzi
