### ISSUE TITLE
miq-app image is missing an rpm

### ISSUE THREAD

**Issue by bazulay** [ManageIQ/manageiq-pods#79]
Per commit https://github.com/ManageIQ/manageiq-appliance-build/pull/116/files
openscap-scanner package is required to run openscap on a container image.
when it is not present the SSA for containers will fail.
This is relevant only for upstream.

same issue was opened on the monolithic container (https://github.com/ManageIQ/manageiq/issues/13322)

**Comment by fbladilo** [comment]
Resolved by #80
