### ISSUE TITLE
[feature request] PV-less pods

### ISSUE THREAD

**Issue by vnugent** [ManageIQ/manageiq-pods#81]
Persistent storage requires additional set up tasks (more work) for developers who stand up their own Kubernetes/OpenShift clusters.  I'm proposing a PersistentVolume-less pod.

**Comment by bazulay** [comment]
@vnugent  than you can simply change the template  and if you want to share with all than submit the new template here (it should be simple), we have currently a much higher priorities.
keep in mind that such a setup will not survive reschedule of any of the pods

**Comment by carbonin** [comment]
I'm pretty sure this is just not going to happen. If someone wants to deploy without PVs for a ephemeral setup I would suggest just removing the claims from the template.
