### ISSUE TITLE
bug in miq-template.yaml

### ISSUE THREAD

**Issue by urban-it-solutions** [ManageIQ/manageiq-pods#82]
line 91

 - image: manageiq/manageiq-pods:{APPLICATION_IMG_TAG}

missing a $
-> - image: manageiq/manageiq-pods:${APPLICATION_IMG_TAG}

**Comment by fbladilo** [comment]
@urban-it-solutions Good catch thanks.

@simaishi It looks like we introduce it in [https://github.com/ManageIQ/manageiq-pods/commit/81774f6feb560a9f0637d7f0a15ab8ab03e6712d](here)

**Comment by simaishi** [comment]
Oops, sorry...  That value gets overwritten, which is why the template still works (and we never noticed!)
