### ISSUE TITLE
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied

### ISSUE THREAD

**Issue by haloss1** [ManageIQ/manageiq-pods#820]
Hi, i'm getting `mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied` after install on the PostgreSQL pod

Follow the install instructions
Wait for pods to create
PostgreSQL pod status indicates `CrashLoopBackOff`
```
$ kubectl logs pod/postgresql-b5c85cf7f-hcfzf
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
```

- ManageIQ version: `morphy-1`
- Minikube/KIND/OCP/CRC version: Kubespray
- Kubernetes version: (use `kubectl version`): 
```
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

@miq-bot add-label bug

**Comment by bdunne** [comment]
Usually this happens when the postgres user doesn't have permission to write to the mounted volume.  Check the permissions on the volume and `chmod 777` if necessary.

**Comment by haloss1** [comment]
Ty, i ended up using a external PostgreSQL database and now i can get all the pods to successfully deploy :)

**Comment by mkumatag** [comment]
Even I'm hitting with this error, not sure how can I fix the volume permission for the operator based deployment! any idea how to fix this error?
