### ISSUE TITLE
1-remote-console pod keeps restarting after installing IM on IA

### ISSUE THREAD

**Issue by bsogithub** [ManageIQ/manageiq-pods#829]
According to Brandon, the readiness and liveness probes are trying to hit /ping on port 4000, but nothing is listening there.

The issue may be introduced by https://github.com/ManageIQ/manageiq/pull/21766 and https://github.com/ManageIQ/manageiq-pods/pull/825

- ManageIQ version: 2.0.0.20220315141852_3fb1aa5
- Minikube/KIND/OCP/CRC version: OCP 4.8.27
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v0.21.0-beta.1", GitCommit:"88e7eba36ac7cc026d064bb6e4a988acc18a144e", GitTreeState:"clean", BuildDate:"2021-12-14T17:29:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6+bb8d50a", GitCommit:"cefce093e4e5bc9a1916eb5a489ed37c7d467f6f", GitTreeState:"clean", BuildDate:"2021-12-21T06:22:19Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`):
NAME="Red Hat Enterprise Linux"
VERSION="8.5 (Ootpa)"

**Comment by Fryguy** [comment]
https://github.com/ManageIQ/manageiq/pull/21766 and https://github.com/ManageIQ/manageiq-pods/pull/825 haven't been brought back to najdorf, so this could only happen on master.  Are you seeing it on master?

**Comment by bsogithub** [comment]
Yes. It is on master. Sorry forgot to mention it.

**Comment by bdunne** [comment]
Fixed by:
- https://github.com/ManageIQ/manageiq/pull/21809
- https://github.com/ManageIQ/manageiq-pods/pull/832
- https://github.com/ManageIQ/manageiq-documentation/pull/1657

**Comment by Fryguy** [comment]
@bdunne Can this be closed now?

**Comment by bdunne** [comment]
Yes
