### ISSUE TITLE
Unable to login to Manageiq instance

### ISSUE THREAD

**Issue by srujan07** [ManageIQ/manageiq-pods#864]
Hi Team,

We have deployed "**manageiq-operator**" in a GKE cluster and facing issues login to the instance with the default credentials(admim/smartvm). There were no errors in any of the pod logs. Can anyone please help. 

Followed instructions provided here https://github.com/ManageIQ/manageiq-pods/tree/master/manageiq-operator

- ManageIQ version: **latest-najdorf**
- Kubernetes version: (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.10-gke.600", GitCommit:"2c921d7b040ed9c5a3a1f9407fb109b74d72d0a4", GitTreeState:"clean", BuildDate:"2022-06-02T09:20:24Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}

```
FYI, I am using ingress URL to access manageiq.  Below are the list of pods deplpyed in manageiq namespace.

```
NAME                               READY   STATUS    RESTARTS   AGE
1-event-handler-56d5b9c6f6-l2jqn   1/1     Running   0          6d6h
1-generic-5d4d469865-27jjg         1/1     Running   0          6d6h
1-generic-5d4d469865-z49sm         1/1     Running   0          6d6h
1-priority-5c9d78c79f-cvzgn        1/1     Running   0          6d6h
1-priority-5c9d78c79f-ln468        1/1     Running   0          6d6h
1-remote-console-899fffcdf-6f96z   1/1     Running   0          6d6h
1-reporting-84f944c77f-q7jsf       1/1     Running   0          6d6h
1-reporting-84f944c77f-sn976       1/1     Running   0          6d6h
1-schedule-6f4f48c749-9rz75        1/1     Running   0          6d6h
1-ui-d69db99b-bpnkh                1/1     Running   0          6d6h
1-ui-d69db99b-kngtc                1/1     Running   0          6d6h
1-web-service-58949b6d6-jd5sr      1/1     Running   0          6d6h
1-web-service-58949b6d6-nf9md      1/1     Running   0          6d6h
httpd-6fbd8ff9bd-lmjgz             1/1     Running   0          30h
memcached-d9dc4d698-xcwr9          1/1     Running   0          6d6h
orchestrator-89fc5ff8c-b2ddv       1/1     Running   0          6d6h
postgresql-56648857bc-844w8        1/1     Running   0          6d6h
```
List of services :

```
NAME                        TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)             AGE
httpd                       LoadBalancer   240.224.127.68   35.xxx.xxx.xxx   8080:31496/TCP      6d7h
manageiq-operator-metrics   ClusterIP      240.224.71.158   <none>           8383/TCP,8686/TCP   6d7h
memcached                   ClusterIP      240.224.40.20    <none>           11211/TCP           6d7h
postgresql                  ClusterIP      240.224.19.254   <none>           5432/TCP            6d7h
remote-console              ClusterIP      240.224.62.164   <none>           3000/TCP            6d7h
ui                          ClusterIP      240.224.0.191    <none>           3000/TCP            6d7h
web-service                 ClusterIP      240.224.12.237   <none>           3000/TCP            6d7h
```

Ingress:

```
NAME    CLASS    HOSTS                         ADDRESS          PORTS     AGE
httpd   <none>   miqproject.apps-crc.testing   34.111.xxx.xxx   80, 443   6d7h
```

Thanks in advance,
Srujan.

@miq-bot add-label bug

**Comment by srujan07** [comment]
Also, the UI doesn't seem to be loading the images while accessing ingress URL, however it works fine when I access the https service ip directly. Not sure what's missing in our config. 

<img width="251" alt="Screenshot 2022-08-03 at 11 06 56 PM" src="https://user-images.githubusercontent.com/25569589/182673190-0d0ee8fe-52cb-4e77-8fe8-bbd818a78a56.png">
CR used for our deplpyment: 

```
apiVersion: manageiq.org/v1alpha1
kind: ManageIQ
metadata:
  name: miq
spec:
  applicationDomain: miqproject.apps-crc.testing
```

**Comment by Fryguy** [comment]
@bdunne Can you take a look at this one?

**Comment by srujan07** [comment]
@bdunne Can you please help me on this?

**Comment by bdunne** [comment]
I see that the ingress hostname is `miqproject.apps-crc.testing`, but you mentioned that you're running in a GKE cluster.  I think you need to set the `applicationDomain` in the ManageIQ CR to a hostname that points to your cluster ingress.

**Comment by srujan07** [comment]
@bdunne Thanks for your response. I tried using the default domain and the operator has created an ingress for that domain in our GKE cluster. 

```
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      ingress.kubernetes.io/backends: '{"k8s-be-30185--b9c71286ead57546":"HEALTHY","k8s-be-31496--b9c71286ead57546":"HEALTHY"}'
      ingress.kubernetes.io/force-ssl-redirect: "false"
      ingress.kubernetes.io/forwarding-rule: k8s2-fr-ak08hblu-manageiq-httpd-6mm9v3mj
      ingress.kubernetes.io/https-forwarding-rule: k8s2-fs-ak08hblu-manageiq-httpd-6mm9v3mj
      ingress.kubernetes.io/https-target-proxy: k8s2-ts-ak08hblu-manageiq-httpd-6mm9v3mj
      ingress.kubernetes.io/ssl-cert: k8s2-cr-ak08hblu-wzavbawgf9yy5hzg-8eb70b1a05093294
      ingress.kubernetes.io/static-ip: k8s2-fr-ak08hblu-manageiq-httpd-6mm9v3mj
      ingress.kubernetes.io/target-proxy: k8s2-tp-ak08hblu-manageiq-httpd-6mm9v3mj
      ingress.kubernetes.io/url-map: k8s2-um-ak08hblu-manageiq-httpd-6mm9v3mj
      kubernetes.io/ingress.allow-http: "true"
    creationTimestamp: "2022-07-28T10:23:47Z"
    finalizers:
    - networking.gke.io/ingress-finalizer-V2
    generation: 3
    labels:
      app: manageiq
    name: httpd
    namespace: manageiq
    ownerReferences:
    - apiVersion: manageiq.org/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: ManageIQ
      name: miq
      uid: 271fd88d-dd99-455a-8d5f-d188ffb5f968
    resourceVersion: "81428953"
    uid: 5623dcb1-1fee-4e1b-8c3d-f34e7e60c42b
  spec:
    rules:
    - host: miqproject.apps-crc.testing
      http:
        paths:
        - backend:
            service:
              name: httpd
              port:
                number: 8080
          path: /
          pathType: ImplementationSpecific
    tls:
    - hosts:
      - miqproject.apps-crc.testing
      secretName: tls-secret
  status:
    loadBalancer:
      ingress:
      - ip: 34.xxx.xxx.xxx
```

We have also tried using our own domain with the custom certs but still we see the same behaviour.  However, I suspect the issue could be with the configuration in httpd.conf. Can you please verify if the below config looks good.

https://paste.opendev.org/show/bnhfNFihea9CWc7ATmyR/

**Comment by bdunne** [comment]
The host on the ingress is incorrect, you can change it by setting the `applicationDomain` on the ManageIQ CR.

**Comment by srujan07** [comment]
Please find the updated ingress config here after setting our own applicationDomain in the CR. 
https://paste.opendev.org/show/b0nLBb4fGC3yM9gaJvlv/

**Comment by bdunne** [comment]
When you changed it to use your domain:
- Did the ingress reflect that?
- Was the httpd config updated?
- Did the httpd pod get redeployed?

**Comment by srujan07** [comment]
Sorry, I should have made it clear. I did a fresh installation with our domain and certs in a different namespace in the same cluster. There is no difference in the httpd config file.

**Comment by srujan07** [comment]
@bdunne Any update on this please?

**Comment by srujan07** [comment]
@Fryguy @bdunne We are blocked on this. Appreciate if you can provide some help. :)

**Comment by bdunne** [comment]
I don't have a GKE cluster to test with at the moment, but are you able to get it working without the custom certificates?

**Comment by srujan07** [comment]
@bdunne No, it wasn't working with default certs which is why we had to try with custom certs to see if that helps, but no luck. Do you have any reference links to deploy this operator in minikube so that I can give it a try?

**Comment by bdunne** [comment]
I'm in the process of moving the documentation from the READMEs to our official documentation, but you can take a look at it [here](https://github.com/ManageIQ/manageiq-documentation/pull/1656).  I typically test with OpenShift, but I've also used K3S. You may need to bring your own cluster ingress, I've used https://docs.nginx.com/nginx-ingress-controller/ in the past
