### ISSUE TITLE
Initial MIQ deployments will not start on OCP 3.4 or Origin 1.4

### ISSUE THREAD

**Issue by fbladilo** [ManageIQ/manageiq-pods#87]
@bazulay @simaishi As of OCP 3.4 and origin 1.4 , the default behavior of the imageChange trigger has changed. Images are NOT automatically resolved as they did in (3.3 and 1.3) when set to automatic=false. This causes the initial deployments to stay idle and not start.

We need to revert the templates to use automatic=true on imageChangeParams for all PODs and instruct users to disable it after a successful initial deployment on documentation.

**Comment by bazulay** [comment]
And we need to update the documentation as well

**Comment by fbladilo** [comment]
@bazulay Yes, will put a warning on documentation to disable the triggers after a successful deployment.
