### ISSUE TITLE
Setting the ManageIQ hostname as CN in the SSL Certificate

### ISSUE THREAD

**Issue by simon3z** [ManageIQ/manageiq-pods#92]
Currently the SSL certificate used by the ManageIQ app doesn't contain a valid hostname as CN and there is no way to properly configure it during deployment.

E.g.:
```
* Server certificate:
* 	subject: CN=server,OU=Licensing,O=ManageIQ,C=US
* 	start date: Apr 13 21:47:19 2008 GMT
* 	expire date: Apr 11 21:47:19 2018 GMT
* 	common name: server
* 	issuer: CN=ca,OU=Licensing,O=ManageIQ,C=US
```

Since the route is automatically generated I suppose the same host used there should be configured by default (with an option to override or add other hostnames).

Technically this could be implemented in two ways:

* During deployment instruct ManageIQ initialization to use the correct hostname in the generation of the certificate
* Use a reencrypt route managed by OpenShift

In either case I think you should also consider to allow to provide a the certificate as an option (probably in the second approach with reencrypt is more straight-forward).

cc @bazulay @fbladilo

**Comment by fbladilo** [comment]
@simon3z Sounds good, let me discuss with @bazulay, I'm inclined over the reencrypt route choice which we could potentially provide a route template to use and change. 
BTW , we offer control over the hostname exposed in the route via APPLICATION_DOMAIN (by default empty).
```
[root@franco-master-ocp34 /]# oc process cloudforms-brew-57 --parameters | grep APPLICATION_DOMAIN
APPLICATION_DOMAIN            The exposed hostname that will route to the application service, if left blank a value will be defaulted.                       
```

**Comment by fbladilo** [comment]
@simon3z @bazulay BTW, I'm not sure how that cert is actually getting created (certainly not baked in the image), I believe during EVM startup when it brings up httpd, it happens. 
@carbonin probably knows more about this..

**Comment by bazulay** [comment]
@fbladilo @simon3z @carbonin 
Doing the reencrypt is definitly easier,
I would also check what other applications are doing.
@fbladilo  I would say that the reencrypt part should get in ASAPto master, otherwise access to the AP entry pont  of manageiq is problematic,
And after that investigate the other option.

@simon3z  Is this approach o.k. with you ?

**Comment by simon3z** [comment]
@bazulay yes, although IIRC for the reencrypt you still need to provide the expected CA for the internal endpoint (not sure how tricky is that or if it can be disabled).

**Comment by carbonin** [comment]
@fbladilo I believe you're talking about [this](https://github.com/ManageIQ/manageiq/blob/master/certs/server.cer) right? In which case, yeah it's just in the source tree.

I believe the appliance_console has some options around managing certificates, but I'm not very familiar with them.

**Comment by joelddiaz** [comment]
@simon3z with the most recent versions of OpenShift (3.6), there is no need to define the destinationCACertificate field. See this example: https://github.com/zgalor/openshift-ansible/blob/prometheus-role/roles/openshift_prometheus/tasks/install_prometheus.yaml#L101-L111

FWIW, I tried this with OpenShift version oc v3.6.173.0.5 / kubernetes v1.6.1+5115d708d7

**Comment by fbladilo** [comment]
@simon3z @bazulay We moved all internal SSL to the route, see #197 #199 , updated README with instructions accordingly.
