### ISSUE TITLE
images built from manageiq master should not trigger upgrade seaquence every reschedule

### ISSUE THREAD

**Issue by bazulay** [ManageIQ/manageiq-pods#93]
While this behavior is the right behavior for development env, this is not necessarily the right way to behave on a real live system.
On one live system  based on manageiq master, the system got into a reschedule storm , and as a result it run out of space on the PV since it is backing up the data every time it thinks it is in upgrade seaquence, and on master we have always assumed a reschedule = upgrade

optional solution:
The system should base the decision whether it is in upgrade seaquence  (on images built from master) based also on the also on the persisted revision (sha) of manageiq git repo

**Comment by fbladilo** [comment]
@bazulay Yes, master has been always an exception since it is considered to be for development purposes. Treating master as a regular release might induce more work from the developer side but I guess is doable.

**Comment by fbladilo** [comment]
Resolved by #101
