### ISSUE TITLE
Make sure cockpit-ws is built into the PODified manageiq image

### ISSUE THREAD

**Issue by bazulay** [ManageIQ/manageiq-pods#97]
Per https://github.com/ManageIQ/manageiq/pull/12506
and https://github.com/ManageIQ/manageiq-appliance/pull/107

We need to make sure cockpit-ws if fully functional on the podified version.

**Comment by simaishi** [comment]
Also need a new package: https://github.com/ManageIQ/manageiq-appliance-build/pull/192

**Comment by bazulay** [comment]
@simaishi @fbladilo 

It is a bit more than just installing the rpm .... we need to make sure it actually works on the PODified deployment.

**Comment by fbladilo** [comment]
@simaishi @bazulay A couple of things on this one : 

* We need at least the cockpit RPM included in monolithic and openshift images
* We actually git-clone appliance-build so once  https://github.com/ManageIQ/manageiq-appliance/pull/107 is merged , we should be good.

**Comment by fbladilo** [comment]
@bazulay We wait on this one until cockpit related PRs are actually merged upstream in manageiq/manageiq-appliance repos.

**Comment by fbladilo** [comment]
@carbonin @simaishi This one seems stale? Were the relevant cockpit PRs merged already? Any ideas how to validate this on podified?

**Comment by bazulay** [comment]
@fbladilo  @gtanzillo  @carbonin @simaishi

The code was merged , but still not validated on the regular appliance,
When the feedback is provides we could validate it on the PODified.

**Comment by fbladilo** [comment]
Thanks Barak, let us know so we can test and clean this one up.

**Comment by chessbyte** [comment]
Seems like all the code got in, but never validated.  Closing this stale issue and will accept incoming bugs when someone finds issues.
