### ISSUE TITLE
Log rotation does not work in both PODified and Monolithic ManageIQ 

### ISSUE THREAD

**Issue by bazulay** [ManageIQ/manageiq-pods#98]

**Comment by fbladilo** [comment]
@bazulay What is the official appliance procedure for log rotation? Is there one? We should not go for a one-off only on podified MIQ.

**Comment by bazulay** [comment]
added @jvlcek who worked on the log rotation,
As far as I understand there is only a mechanism for that upstream.

**Comment by simaishi** [comment]
Ah, sorry, I missed the mention...  The log rotate config file is there (/etc/logratote.d/miq_logs.conf), but I don't see `logrotate` package being installed in container images. Would this be just a matter of installing the package?

@jvlcek On my vSphere appliance, I have `logrotate` installed, but as a dependency of some other package. If our feature depends on this package, it should probably be installed explicitly.

**Comment by bazulay** [comment]
@simaishi @fbladilo  I think this work was only merged upstream ...
this is why I added @jvlcek

**Comment by fbladilo** [comment]
@simaishi @bazulay Logrotate configs are already being pushed by the appliance repo : 

```[root@manageiq-1-bgzon logrotate.d]# cat miq_logs.conf 
/var/www/miq/vmdb/log/*.log /var/www/miq/vmdb/log/apache/*.log /var/opt/rh/rh-postgresql95/lib/pgsql/data/pg_log/*.log {
  daily
  dateext
  missingok
  rotate 14
  notifempty
  compress
  copytruncate
  prerotate
    source /etc/default/evm; /bin/sh ${APPLIANCE_SOURCE_DIRECTORY}/logrotate_free_space_check.sh $1
  endscript
  lastaction
    /sbin/service httpd reload > /dev/null 2>&1 || true
  endscript
}
```
The config looks reasonable, it has "missingok" which we need since our PG logs are not local, also an httpd reload will not incurr issues with the probes, a restart would have been harder to digest. 
We just need to install the package for upstream which I'm ok with.

**Comment by fbladilo** [comment]
@simaishi Do we logrotate on downstream builds?

**Comment by bazulay** [comment]
@fbladilo @simaishi @carbonin @loicavenel

Trying to answer some of your questions:
1 - need to find out how are things working downstream
2 - we logrotate only to save space (and by that allow the appliance to have a longer ;life before running out of space)
3 - I am not sure how the combination of openshift scheduled jobs work with PetSets (soon to be statefulSets) ...does it work per appliance ?
4 - when unsure I will use crond for now , as we depend anyway on systemd and this does not seem to go away soon

**Comment by jvlcek** [comment]
Just to clarify what log rotation functionality is where:

## For a long time:

- Log rotation has been in the product for a long time, both upstream and downstream, with
the following functionality:
-- The log rotation requires logfile_size+(logfile_size/5) disk space to rotate the log
-- A cron job is run daily to rotate and compress the logs. Lacking available disk space will prevent log rotations.
-- 14 daily compressed rotations are saved, with the 15oldest being deleted by the
    daily cron job.

## What has change recently:

At the end of 2016 I introduced two different logfile rotation configuration options
to the appliance_console.

**1 -**
https://github.com/ManageIQ/manageiq/pull/12027 has added functionality to the appliance_console that allows users to configure an additional disk, already configured on the VM, as the destination for log files. Presumably a larger disk allowing more than 14 daily
rotations to be maintained.

This PR is in both upstream and downstream.

**2 -**
https://github.com/ManageIQ/manageiq/pull/12293 has added functionality to the appliance_console that allows users to configure a number besides the default
of 14, of saved compressed logfile rotations to be kept on disk.
This functionality, combined with the previously described PR, would allow for
more than 14 daily rotations to be maintained on a larger disk volume.

This PR is in only upstream.

## Note:

The user must use the appliance_console to explicitly take advantage of the two
new configuration options. So by default a cron job should run daily to rotate
the log files, maintaining 14.

**Comment by fbladilo** [comment]
@jvlcek Thanks for clarification! 

@bazulay I'm inclined to enable the default 14-day rotation via standard cron jobs as it is on the rest of builds, we already supply a PV for server data. I'm not sure about the support of Openshift cron jobs on petsets, also logrotate cron jobs actually perform more than just moving files on the PVs, they also interact with daemons (httpd) which might not be possible at all.

**Comment by bazulay** [comment]
@fbladilo 
I agree this is the best approach we can work with now.
